// Auto-generated by generate-napi-types.mjs
// DO NOT EDIT MANUALLY

/**
 * 订阅用户在线状态.
 * @param operationID - 唯一操作标识
 * @param userIDs - 用户ID列表
 * @returns Promise<string>
 */
export function subscribeUsersStatus(operationID: string, userIDs: string): Promise<string>;

/**
 * 取消订阅用户在线状态.
 * @param operationID - 唯一操作标识
 * @param userIDs - 用户ID列表
 * @returns Promise<string>
 */
export function unSubscribeUsersStatus(operationID: string, userIDs: string): Promise<string>;

/**
 * 获取订阅的用户在线状态.
 * @param operationID - 唯一操作标识
 * @returns Promise<string>
 */
export function getSubscribeUsersStatus(operationID: string): Promise<string>;

/**
 * 获取指定用户在线状态.
 * @param operationID - 唯一操作标识
 * @param userIDs - 用户ID列表
 * @returns Promise<string>
 */
export function getUserStatus(operationID: string, userIDs: string): Promise<string>;

/**
 * 获取用户信息.
 * @param operationID - 唯一操作标识
 * @param userIDs - 用户ID列表
 * @returns Promise<string>
 */
export function getUsersInfo(operationID: string, userIDs: string): Promise<string>;

/**
 * 设置我的信息.
 * @param operationID - 唯一操作标识
 * @param userInfo - 用户信息
 * @returns Promise<string>
 */
export function setSelfInfo(operationID: string, userInfo: string): Promise<string>;

/**
 * 获取我的信息.
 * @param operationID - 唯一操作标识
 * @returns Promise<string>
 */
export function getSelfUserInfo(operationID: string): Promise<string>;

/**
 * 设置APP角标.
 * @param operationID - 唯一操作标识
 * @param appUnreadCount - 未读数量
 * @returns Promise<string>
 */
export function setAppBadge(operationID: string, appUnreadCount: number): Promise<string>;

/**
 * 创建文本消息.
 * @param operationID - 唯一操作标识
 * @param text - 文本内容
 * @returns string
 */
export function createTextMessage(operationID: string, text: string): string;

/**
 * 创建高级文本消息.
 * @param operationID - 唯一操作标识
 * @param text - 唯一操作标识
 * @param messageEntityList - 消息实例列表
 * @returns string
 */
export function createAdvancedTextMessage(operationID: string, text: string, messageEntityList: string): string;

/**
 * 创建At消息.
 * @param operationID - 唯一操作标识
 * @param text - 唯一操作标识
 * @param atUserList - 唯一操作标识
 * @param atUsersInfo - 唯一操作标识
 * @param message - 唯一操作标识
 * @returns string
 */
export function createTextAtMessage(operationID: string, text: string, atUserList: string, atUsersInfo: string,
  message: string): string;

/**
 * 创建位置消息.
 * @param operationID - 唯一操作标识
 * @param description - 描述
 * @param longitude - 经度
 * @param latitude - 维度
 * @returns string
 */
export function createLocationMessage(operationID: string, description: string, longitude: number,
  latitude: number): string;

/**
 * 创建自定义消息.
 * @param operationID - 唯一操作标识
 * @param data - 文本内容
 * @param extension - 扩展内容
 * @param description - 描述内容
 * @returns string
 */
export function createCustomMessage(operationID: string, data: string, extension: string, description: string): string;

/**
 * 创建引用消息.
 * @param operationID - 唯一操作标识
 * @param data - 文本内容
 * @param message - 被引用的消息
 * @returns string
 */
export function createQuoteMessage(operationID: string, data: string, message: string): string;

/**
 * 创建高级引用消息.
 * @param operationID - 唯一操作标识
 * @param data - 文本内容
 * @param message - 被引用的消息
 * @param messageEntityList - 消息实例列表
 * @returns string
 */
export function createAdvancedQuoteMessage(operationID: string, data: string, message: string,
  messageEntityList: string): string;

/**
 * 创建卡片消息.
 * @param operationID - 唯一操作标识
 * @param cardInfo - 卡片内容
 * @returns string
 */
export function createCardMessage(operationID: string, cardInfo: string): string;

/**
 * 创建本地路径视频消息.
 * @param operationID - 唯一操作标识
 * @param videoFullPath - 文件绝对路径
 * @param videoType - 视频类型
 * @param duration - 视频时长
 * @param snapshotFullPath - 预览图绝对路径
 * @returns string
 */
export function createVideoMessageFromFullPath(operationID: string, videoFullPath: string, videoType: string,
  duration: number, snapshotFullPath: string): string;

/**
 * 创建本地路径图片消息.
 * @param operationID - 唯一操作标识
 * @param imageFullPath - 文件绝对路径
 * @returns string
 */
export function createImageMessageFromFullPath(operationID: string, imageFullPath: string): string;

/**
 * 创建本地路径语音消息.
 * @param operationID - 唯一操作标识
 * @param soundPath - 文件绝对路径
 * @param duration - 音频时长
 * @returns string
 */
export function createSoundMessageFromFullPath(operationID: string, soundPath: string, duration: number): string;

/**
 * 创建本地路径文件消息.
 * @param operationID - 唯一操作标识
 * @param fileFullPath - 文件绝对路径
 * @param fileName - 文件名称
 * @returns string
 */
export function createSoundMessageFromFullPath(operationID: string, fileFullPath: string, fileName: string): string;

/**
 * 创建图片文件消息.
 * @param operationID - 唯一操作标识
 * @param imagePath - 文件本地绝对路径
 * @returns string
 */
export function createImageMessage(operationID: string, imagePath: string): string;

/**
 * 创建URL地址图片消息.
 * @param operationID - 唯一操作标识
 * @param sourcePath - 源文件绝对路径
 * @param sourcePicture - 原图相关信息
 * @param bigPicture - 大图相关信息
 * @param snapshotPicture - 缩略图相关信息
 * @returns string
 */
export function createImageMessageByUrl(operationID: string, sourcePath: string, sourcePicture: string,
  bigPicture: string, snapshotPicture: string): string;

/**
 * 创建URL地址音频消息.
 * @param operationID - 唯一操作标识
 * @param sourcePath - 源文件URL
 * @returns string
 */
export function createSoundMessageByUrl(operationID: string, sourcePath: string): string;

/**
 * 创建本地地址音频消息.
 * @param operationID - 唯一操作标识
 * @param sourcePath - 源文件绝对路径
 * @param duration - 时长
 * @returns string
 */
export function createSoundMessage(operationID: string, sourcePath: string, duration: number): string;

/**
 * 创建URL地址视频消息.
 * @param operationID - 唯一操作标识
 * @param videoBaseInfo - 视频信息
 * @returns string
 */
export function createVideoMessageByUrl(operationID: string, videoBaseInfo: string): string;

/**
 * 创建视频消息.
 * @param operationID - 唯一操作标识
 * @param videoPath - 视频绝对信息
 * @param videoType - 视频类型
 * @param duration - 视频时长
 * @param snapshotPath - 视频缩略图
 * @returns string
 */
export function createVideoMessage(operationID: string, videoPath: string, videoType: string, duration: number,
  snapshotPath: string): string;

/**
 * 创建URL地址文件消息.
 * @param operationID - 唯一操作标识
 * @param fileBaseInfo - 文件信息
 * @returns string
 */
export function createFileMessageByUrl(operationID: string, fileBaseInfo: string): string;

/**
 * 创建文件消息.
 * @param operationID - 唯一操作标识
 * @param filePath - 文件绝对路径
 * @param fileName - 文件名称
 * @returns string
 */
export function createFileMessage(operationID: string, filePath: string, fileName: string): string;

/**
 * 创建合并消息.
 * @param operationID - 唯一操作标识
 * @param messageList - 消息列表
 * @param title - 标题
 * @param summaryList - 子标题列表
 * @returns string
 */
export function createMergerMessage(operationID: string, messageList: string, title: string,
  summaryList: string): string;

/**
 * 创建表情消息.
 * @param operationID - 唯一操作标识
 * @param index - 表情索引
 * @param data - 表情数据
 * @returns string
 */
export function createFaceMessage(operationID: string, index: number, data: string): string;

/**
 * 创建转发消息.
 * @param operationID - 唯一操作标识
 * @param data - 转发的消息
 * @returns string
 */
export function createForwardMessage(operationID: string, data: string): string;

/**
 * 发送消息.
 * @param operationID - 唯一操作标识
 * @param message -
 * @param recvID -
 * @param groupID -
 * @param offlinePush -
 * @param isOnlineOnly -
 * @param operationID -
 * @param onProgress - 进度回调 {progress: number, message: MessageItem}
 * @returns Promise<string>
 */
export function sendMessage(operationID: string, message: string, recvID: string, groupID: string, offlinePush: string,
  isOnlineOnly: boolean, onProgress: (data: string) => void): Promise<string>;

/**
 * 发送消息.
 * @param operationID - 唯一操作标识
 * @param message -
 * @param recvID -
 * @param groupID -
 * @param offlinePush -
 * @param isOnlineOnly -
 * @param operationID -
 * @param onProgress - 进度回调 {progress: number, message: MessageItem}
 * @returns Promise<string>
 */
export function sendMessageNotOss(operationID: string, message: string, recvID: string, groupID: string,
  offlinePush: string, isOnlineOnly: boolean, onProgress: (data: string) => void): Promise<string>;

/**
 * 查询消息列表.
 * @param operationID - 唯一操作标识
 * @param findMessageOptions - 搜索参数
 * @returns Promise<string>
 */
export function findMessageList(operationID: string, findMessageOptions: string): Promise<string>;

/**
 * 查询高级消息列表.
 * @param operationID - 唯一操作标识
 * @param getMessageOptions - 搜索参数
 * @returns Promise<string>
 */
export function getAdvancedHistoryMessageList(operationID: string, getMessageOptions: string): Promise<string>;

/**
 * 反序查询高级消息列表.
 * @param operationID - 唯一操作标识
 * @param getMessageOptions - 搜索参数
 * @returns Promise<string>
 */
export function getAdvancedHistoryMessageListReverse(operationID: string, getMessageOptions: string): Promise<string>;

/**
 * 撤回消息.
 * @param operationID - 唯一操作标识
 * @param conversationID - 会话ID
 * @param clientMsgID - 消息ID
 * @returns Promise<string>
 */
export function revokeMessage(operationID: string, conversationID: string, clientMsgID: string): Promise<string>;

/**
 * 输入状态更新.
 * @param operationID - 唯一操作标识
 * @param recvID - 接收者ID
 * @param msgTip - 提示消息
 * @returns Promise<string>
 */
export function typingStatusUpdate(operationID: string, recvID: string, msgTip: string): Promise<string>;

/**
 * 会话消息标记为已读.
 * @param operationID - 唯一操作标识
 * @param conversationID - 会话ID
 * @returns Promise<string>
 */
export function markConversationMessageAsRead(operationID: string, conversationID: string): Promise<string>;

/**
 * 删除本地消息.
 * @param operationID - 唯一操作标识
 * @param conversationID - 会话ID
 * @param clientMsgID - 消息ID
 * @returns Promise<string>
 */
export function deleteMessageFromLocalStorage(operationID: string, conversationID: string,
  clientMsgID: string): Promise<string>;

/**
 * 删除消息.
 * @param operationID - 唯一操作标识
 * @param conversationID - 会话ID
 * @param clientMsgID - 消息ID
 * @returns Promise<string>
 */
export function deleteMessage(operationID: string, conversationID: string, clientMsgID: string): Promise<string>;

/**
 * 隐藏所有会话.
 * @param operationID - 唯一操作标识
 * @returns Promise<string>
 */
export function hideAllConversations(operationID: string): Promise<string>;

/**
 * 删除本地及服务器的所有消息.
 * @param operationID - 唯一操作标识
 * @returns Promise<string>
 */
export function deleteAllMsgFromLocalAndSvr(operationID: string): Promise<string>;

/**
 * 删除本地的所有消息.
 * @param operationID - 唯一操作标识
 * @returns Promise<string>
 */
export function deleteAllMsgFromLocal(operationID: string): Promise<string>;

/**
 * 清除会话及删除会话的所有消息.
 * @param operationID - 唯一操作标识
 * @param conversationID - 会话ID
 * @returns Promise<string>
 */
export function clearConversationAndDeleteAllMsg(operationID: string, conversationID: string): Promise<string>;

/**
 * 删除会话及删除会话的所有消息.
 * @param operationID - 唯一操作标识
 * @param conversationID - 会话ID
 * @returns Promise<string>
 */
export function deleteConversationAndDeleteAllMsg(operationID: string, conversationID: string): Promise<string>;

/**
 * 插入单聊消息到本地.
 * @param operationID - 唯一操作标识
 * @param message -
 * @param recvID -
 * @param sendID -
 * @returns Promise<string>
 */
export function insertSingleMessageToLocalStorage(operationID: string, message: string, recvID: string,
  sendID: string): Promise<string>;

/**
 * 插入群聊消息到本地.
 * @param operationID - 唯一操作标识
 * @param message -
 * @param groupID -
 * @param sendID -
 * @returns Promise<string>
 */
export function insertGroupMessageToLocalStorage(operationID: string, message: string, groupID: string,
  sendID: string): Promise<string>;

/**
 * 搜索本地消息.
 * @param operationID - 唯一操作标识
 * @param searchParam - 搜索参数
 * @returns Promise<string>
 */
export function searchLocalMessages(operationID: string, searchParam: string): Promise<string>;

/**
 * 设置消息本地ex字段.
 * @param operationID - 唯一操作标识
 * @param conversationID - 会话ID
 * @param clientMsgID - 消息ID
 * @param localEx - 扩展字段内容
 * @returns Promise<string>
 */
export function setMessageLocalEx(operationID: string, conversationID: string, clientMsgID: string,
  localEx: string): Promise<string>;

/**
 * 改变输入状态.
 * @param operationID - 唯一操作标识
 * @param conversationID - 会话ID
 * @param inputStatus - 输入状态
 * @returns Promise<string>
 */
export function changeInputStates(operationID: string, conversationID: string, inputStatus: boolean): Promise<string>;

/**
 * 获取输入状态.
 * @param operationID - 唯一操作标识
 * @param conversationID - 会话ID
 * @param userID - 用户ID
 * @returns Promise<string>
 */
export function getInputStates(operationID: string, conversationID: string, userID: string): Promise<string>;

/**
 * 初始化SDK.
 * @param operationID - 唯一操作标识
 * @param config - 配置参数
 * @returns number
 */
export function initSdk(operationID: string, config: string): number;

/**
 * 反初始化SDK.
 * @param operationID - 唯一操作标识
 * @returns Promise<string>
 */
export function unInitSdk(operationID: string): void;

/**
 * 登录.
 * @param operationID - 唯一操作标识
 * @param userID - 用户ID
 * @param token - token
 * @returns Promise<string>
 */
export function login(operationID: string, userID: string, token: string): Promise<string>;

/**
 * 登出.
 * @param operationID - 唯一操作标识
 * @returns Promise<string>
 */
export function logout(operationID: string): Promise<string>;

/**
 * 设置后台运行状态.
 * @param operationID - 唯一操作标识
 * @param isBackground - 是否后台运行
 * @returns Promise<string>
 */
export function setAppBackgroundStatus(operationID: string, isBackground: boolean): Promise<string>;

/**
 * 连接状态改变.
 * @param operationID - 唯一操作标识
 * @returns Promise<string>
 */
export function networkStatusChanged(operationID: string): Promise<string>;

/**
 * 获取登录状态.
 * @param operationID - 唯一操作标识
 * @returns Promise<string>
 */
export function getLoginStatus(operationID: string): number;

/**
 * 获取当前登录用户.
 * @param operationID - 唯一操作标识
 * @returns Promise<string>
 */
export function getLoginUser(operationID: string): string;

/**
 * 设置连接状态回调监听函数.
 * @param callback - 监听函数
 * @param callback.event - 状态类型
 * @param callback.data - 状态描述
 * @returns void
 */
export function setListener(callback: (event: number, data: string) => void): void;

/**
 * 创建群.
 * @param operationID - 唯一操作标识
 * @param cGroupReqInfo - 群信息
 * @returns Promise<string>
 */
export function createGroup(operationID: string, cGroupReqInfo: string): Promise<string>;

/**
 * 加入群.
 * @param operationID - 唯一操作标识
 * @param cGroupID - 群ID
 * @param cReqMsg - 加入请求
 * @param cJoinSource - 加入来源
 * @param ex - 其他信息
 * @returns Promise<string>
 */
export function joinGroup(operationID: string, cGroupID: string, cReqMsg: string, cJoinSource: number,
  ex: string): Promise<string>;

/**
 * 退出群.
 * @param operationID - 唯一操作标识
 * @param cGroupID - 群ID
 * @returns Promise<string>
 */
export function quitGroup(operationID: string, cGroupID: string): Promise<string>;

/**
 * 解散群.
 * @param operationID - 唯一操作标识
 * @param cGroupID - 群ID
 * @returns Promise<string>
 */
export function dismissGroup(operationID: string, cGroupID: string): Promise<string>;

/**
 * 群禁言设置.
 * @param operationID - 唯一操作标识
 * @param cGroupID - 群ID
 * @param cIsMute - 禁言标识
 * @returns Promise<string>
 */
export function changeGroupMute(operationID: string, cGroupID: string, cIsMute: boolean): Promise<string>;

/**
 * 群成员禁言设置.
 * @param operationID - 唯一操作标识
 * @param cGroupID - 群ID
 * @param cUserID - 成员用户ID
 * @param cMutedSeconds - 禁言时长
 * @returns Promise<string>
 */
export function changeGroupMemberMute(operationID: string, cGroupID: string, cUserID: string,
  cMutedSeconds: number): Promise<string>;

/**
 * 设置群成员信息.
 * @param operationID - 唯一操作标识
 * @param cGroupMemberInfo - 群成员信息
 * @returns Promise<string>
 */
export function setGroupMemberInfo(operationID: string, cGroupMemberInfo: string): Promise<string>;

/**
 * 获取已加入群列表.
 * @param operationID - 唯一操作标识
 * @returns Promise<string>
 */
export function getJoinedGroupList(operationID: string): Promise<string>;

/**
 * 获取已加入群列表.
 * @param operationID - 唯一操作标识
 * @param offset - 页码
 * @param count - 每页大小
 * @returns Promise<string>
 */
export function getJoinedGroupListPage(operationID: string, offset: number, count: number): Promise<string>;

/**
 * 获取指定群信息.
 * @param operationID - 唯一操作标识
 * @param cGroupIDList - 群ID列表
 * @returns Promise<string>
 */
export function getSpecifiedGroupsInfo(operationID: string, cGroupIDList: string): Promise<string>;

/**
 * 获取指定群信息.
 * @param operationID - 唯一操作标识
 * @param cSearchParam - 群ID列表
 * @returns Promise<string>
 */
export function searchGroups(operationID: string, cSearchParam: string): Promise<string>;

/**
 * 设置群信息.
 * @param operationID - 唯一操作标识
 * @param cGroupInfo - 群信息
 * @returns Promise<string>
 */
export function setGroupInfo(operationID: string, cGroupInfo: string): Promise<string>;

/**
 * 获取群成员列表.
 * @param operationID - 唯一操作标识
 * @param cGroupInfo - 群信息
 * @param cFilter - 过滤条件
 * @param cOffset - 页码
 * @param cCount - 每页大小
 * @returns Promise<string>
 */
export function getGroupMemberList(operationID: string, cGroupInfo: string, cFilter: number, cOffset: number,
  cCount: number): Promise<string>;

/**
 * 获取群主和群管理员.
 * @param operationID - 唯一操作标识
 * @param cGroupID - 群ID
 * @returns Promise<string>
 */
export function getGroupMemberOwnerAndAdmin(operationID: string, cGroupID: string): Promise<string>;

/**
 * 获取群主和群管理员.
 * @param operationID - 唯一操作标识
 * @param cGroupID - 群ID
 * @param cOffset - 页码
 * @param cCount - 每页大小
 * @param cJoinTimeBegin - 加入起始时间
 * @param cJoinTimeEnd - 加入结束时间
 * @param cFilterUserIDList - 过滤用户列表
 * @returns Promise<string>
 */
export function getGroupMemberListByJoinTimeFilter(operationID: string, cGroupID: string, cOffset: number,
  cCount: number, cJoinTimeBegin: number, cJoinTimeEnd: number, cFilterUserIDList: string): Promise<string>;

/**
 * 获取指定群成员信息.
 * @param operationID - 唯一操作标识
 * @param cGroupID - 群ID
 * @param cUserIDList - 成员ID列表
 * @returns Promise<string>
 */
export function getSpecifiedGroupMembersInfo(operationID: string, cGroupID: string,
  cUserIDList: string): Promise<string>;

/**
 * 移除群成员.
 * @param operationID - 唯一操作标识
 * @param cGroupID - 群ID
 * @param cReason - 原因
 * @param cUserIDList - 成员ID列表
 * @returns Promise<string>
 */
export function kickGroupMember(operationID: string, cGroupID: string, cReason: string,
  cUserIDList: string): Promise<string>;

/**
 * 转让群主.
 * @param operationID - 唯一操作标识
 * @param cGroupID - 群ID
 * @param cNewOwnerUserID - 新群主ID
 * @returns Promise<string>
 */
export function transferGroupOwner(operationID: string, cGroupID: string, cNewOwnerUserID: string): Promise<string>;

/**
 * 转让群主.
 * @param operationID - 唯一操作标识
 * @param cGroupID - 群ID
 * @param cReason - 原因
 * @param cUserIDList - 用户ID列表
 * @returns Promise<string>
 */
export function inviteUserToGroup(operationID: string, cGroupID: string, cReason: string,
  cUserIDList: string): Promise<string>;

/**
 * 获取加入群申请，（接收者）.
 * @param operationID - 唯一操作标识
 * @param req - 请求参数
 * @returns Promise<string>
 */
export function getGroupApplicationListAsRecipient(operationID: string, req: string): Promise<string>;

/**
 * 获取加入群申请，（申请者）.
 * @param operationID - 唯一操作标识
 * @param req - 请求参数
 * @returns Promise<string>
 */
export function getGroupApplicationListAsApplicant(operationID: string, req: string): Promise<string>;

/**
 * 接收加入群申请.
 * @param operationID - 唯一操作标识
 * @param cGroupID - 群ID
 * @param cFromUserID - 申请者ID
 * @param cHandleMsg - 处理信息
 * @returns Promise<string>
 */
export function acceptGroupApplication(operationID: string, cGroupID: string, cFromUserID: string,
  cHandleMsg: string): Promise<string>;

/**
 * 拒绝加入群申请.
 * @param operationID - 唯一操作标识
 * @param cGroupID - 群ID
 * @param cFromUserID - 申请者ID
 * @param cHandleMsg - 处理信息
 * @returns Promise<string>
 */
export function refuseGroupApplication(operationID: string, cGroupID: string, cFromUserID: string,
  cHandleMsg: string): Promise<string>;

/**
 * 获取群加入申请数量.
 * @param operationID - 唯一操作标识
 * @param req - 请求参数
 * @returns Promise<string>
 */
export function getGroupApplicationUnhandledCount(operationID: string, req: string): Promise<string>;

/**
 * 搜索群成员.
 * @param operationID - 唯一操作标识
 * @param cSearchParam - 搜索参数
 * @returns Promise<string>
 */
export function searchGroupMembers(operationID: string, cSearchParam: string): Promise<string>;

/**
 * 是否已加入群.
 * @param operationID - 唯一操作标识
 * @param cGroupID - 群ID
 * @returns Promise<string>
 */
export function isJoinGroup(operationID: string, cGroupID: string): Promise<string>;

/**
 * 获取群指定成员.
 * @param operationID - 唯一操作标识
 * @param cGroupID - 群ID
 * @param userIDList - 成员ID列表
 * @returns Promise<string>
 */
export function getUsersInGroup(operationID: string, cGroupID: string, userIDList: string): Promise<string>;

/**
 * 获取指定好友信息.
 * @param operationID - 唯一操作标识
 * @param userIDList - 好友ID
 * @param filterBlack - 过滤黑名单
 * @returns Promise<string>
 */
export function getSpecifiedFriendsInfo(operationID: string, userIDList: string, filterBlack: boolean): Promise<string>;

/**
 * 获取好友列表.
 * @param operationID - 唯一操作标识
 * @param filterBlack - 过滤黑名单
 * @returns Promise<string>
 */
export function getFriendList(operationID: string, filterBlack: boolean): Promise<string>;

/**
 * 分页获取好友列表.
 * @param operationID - 唯一操作标识
 * @param offset - 页码
 * @param count - 每页大小
 * @param filterBlack - 过滤黑名单
 * @returns Promise<string>
 */
export function getFriendListPage(operationID: string, offset: number, count: number,
  filterBlack: boolean): Promise<string>;

/**
 * 搜索好友.
 * @param operationID - 唯一操作标识
 * @param searchParam - 搜索条件
 * @returns Promise<string>
 */
export function searchFriends(operationID: string, searchParam: string): Promise<string>;

/**
 * 好友检查.
 * @param operationID - 唯一操作标识
 * @param userIDList - 好友ID
 * @returns Promise<string>
 */
export function checkFriend(operationID: string, userIDList: string): Promise<string>;

/**
 * 添加好友.
 * @param operationID - 唯一操作标识
 * @param userIDReqMsg - 好友请求参数
 * @returns Promise<string>
 */
export function addFriend(operationID: string, userIDReqMsg: string): Promise<string>;

/**
 * 更新好友.
 * @param operationID - 唯一操作标识
 * @param userIDReqMsg - 好友请求参数
 * @returns Promise<string>
 */
export function updateFriends(operationID: string, userIDReqMsg: string): Promise<string>;

/**
 * 删除好友.
 * @param operationID - 唯一操作标识
 * @param friendUserID - 好友ID
 * @returns Promise<string>
 */
export function deleteFriend(operationID: string, friendUserID: string): Promise<string>;

/**
 * 获取好友添加请求列表（接受者）.
 * @param operationID - 唯一操作标识
 * @param req - 好友ID
 * @returns Promise<string>
 */
export function getFriendApplicationListAsRecipient(operationID: string, req: string): Promise<string>;

/**
 * 获取好友添加请求申请列表，（申请者）.
 * @param operationID - 唯一操作标识
 * @param req - 好友ID
 * @returns Promise<string>
 */
export function getFriendApplicationListAsApplicant(operationID: string, req: string): Promise<string>;

/**
 * 接受好友添加请求.
 * @param operationID - 唯一操作标识
 * @param userIDHandleMsg - 好友ID
 * @returns Promise<string>
 */
export function acceptFriendApplication(operationID: string, userIDHandleMsg: string): Promise<string>;

/**
 * 拒绝好友添加请求.
 * @param operationID - 唯一操作标识
 * @param userIDHandleMsg - 好友ID
 * @returns Promise<string>
 */
export function refuseFriendApplication(operationID: string, userIDHandleMsg: string): Promise<string>;

/**
 * 获取好友请求未处理数量.
 * @param operationID - 唯一操作标识
 * @param req - 好友ID
 * @returns Promise<string>
 */
export function getFriendApplicationUnhandledCount(operationID: string, req: string): Promise<string>;

/**
 * 添加黑名单.
 * @param operationID - 唯一操作标识
 * @param blackUserID - 黑名单用户ID
 * @param ex - 扩展信息
 * @returns Promise<string>
 */
export function addBlack(operationID: string, blackUserID: string, ex: string): Promise<string>;

/**
 * 获取黑名单列表.
 * @param operationID - 唯一操作标识
 * @returns Promise<string>
 */
export function getBlackList(operationID: string): Promise<string>;

/**
 * 移除黑名单.
 * @param operationID - 唯一操作标识
 * @param removeUserID - 用户ID
 * @returns Promise<string>
 */
export function removeBlack(operationID: string, removeUserID: string): Promise<string>;

/**
 * 获取所有会话列表.
 * @param operationID - 唯一操作标识
 * @returns Promise<string>
 */
export function getAllConversationList(operationID: string): Promise<string>;

/**
 * 分页获取会话列表.
 * @param operationID - 唯一操作标识
 * @param offset - 页码
 * @param count - 每页大小
 * @returns Promise<string>
 */
export function getConversationListSplit(operationID: string, offset: number, count: number): Promise<string>;

/**
 * 获取指定会话.
 * @param operationID - 唯一操作标识
 * @param sessionType - 会话类型
 * @param sourceID - 会话ID
 * @returns Promise<string>
 */
export function getOneConversation(operationID: string, sessionType: number, sourceID: string): Promise<string>;

/**
 * 获取多个会话.
 * @param operationID - 唯一操作标识
 * @param conversationIDList - 会话ID列表
 * @returns Promise<string>
 */
export function getMultipleConversation(operationID: string, conversationIDList: string): Promise<string>;

/**
 * 获取多个会话.
 * @param operationID - 唯一操作标识
 * @param conversationID - 会话ID
 * @param req - 设置参数
 * @returns Promise<string>
 */
export function setConversation(operationID: string, conversationID: string, req: string): Promise<string>;

/**
 * 隐藏会话.
 * @param operationID - 唯一操作标识
 * @param conversationID - 会话ID
 * @returns Promise<string>
 */
export function hideConversation(operationID: string, conversationID: string): Promise<string>;

/**
 * 设置会话草稿.
 * @param operationID - 唯一操作标识
 * @param conversationID - 会话ID
 * @param draftText - 会话ID
 * @returns Promise<string>
 */
export function setConversationDraft(operationID: string, conversationID: string, draftText: string): Promise<string>;

/**
 * 获取消息总未读数量.
 * @param operationID - 唯一操作标识
 * @returns Promise<string>
 */
export function getTotalUnreadMsgCount(operationID: string): Promise<string>;

/**
 * 获取At所有标记.
 * @param operationID - 唯一操作标识
 * @returns Promise<string>
 */
export function getAtAllTag(operationID: string): Promise<string>;

/**
 * 根据指定类型会话ID.
 * @param operationID - 唯一操作标识
 * @param sourceID -
 * @param sessionType - 会话类型
 * @returns Promise<string>
 */
export function getConversationIdBySessionType(operationID: string, sourceID: string,
  sessionType: number): Promise<string>;



/**
 * 上传文件
 * @param operationID - 唯一操作标识
 * @param req - 上传请求 JSON 字符串 (包含 name, contentType, uuid, filepath, cause)
 * @param uploadCallback - 上传进度回调 (progress: number, data: string)
 * @returns Promise<string>
 */
export function uploadFile(operationID: string, req: string, uploadCallback: (progress: number, data: string) => void): Promise<string>;

/**
 * 上传日志
 * @param operationID - 唯一操作标识
 * @param line - 行号
 * @param ex - 扩展信息
 * @param uploadLogProgressCallback - 上传进度回调 (progress: number, data: string)
 * @returns Promise<string>
 */
export function uploadLogs(operationID: string, line: number, ex: string, uploadLogProgressCallback: (progress: number, data: string) => void): Promise<string>;

/**
 * 日志
 * @param operationID - 唯一操作标识
 * @param logLevel - 日志级别
 * @param file - 文件名
 * @param line - 行号
 * @param msgs - 消息内容
 * @param err - 错误信息
 * @param keyAndValue - 键值对 JSON 字符串
 * @returns Promise<string>
 */
export function logs(operationID: string, logLevel: number, file: string, line: number, msgs: string, err: string,
  keyAndValue: string): Promise<string>;