// Auto-generated by generate-napi-types.mjs
// DO NOT EDIT MANUALLY

// ============================================================
// 监听器接口定义 (基于 callback_client.go)
// ============================================================

/**
 * 基础回调接口
 */
export interface BaseCallback {
  onError(errCode: number, errMsg: string): void;
  onSuccess(data: string): void;
}

/**
 * 发送消息回调接口
 */
export interface SendMsgCallBack extends BaseCallback {
  onProgress(progress: number): void;
}

/**
 * 上传文件回调接口
 */
export interface UploadFileCallback {
  open(size: number): void;
  partSize(partSize: number, num: number): void;
  hashPartProgress(index: number, size: number, partHash: string): void;
  hashPartComplete(partsHash: string, fileHash: string): void;
  uploadID(uploadID: string): void;
  uploadPartComplete(index: number, partSize: number, partHash: string): void;
  uploadComplete(fileSize: number, streamSize: number, storageSize: number): void;
  complete(size: number, url: string, typ: number): void;
}

/**
 * 上传日志进度回调接口
 */
export interface UploadLogProgress {
  onProgress(current: number, size: number): void;
}

/**
 * 连接状态监听器接口
 */
export interface ConnListener {
  onConnecting(): void;
  onConnectSuccess(): void;
  onConnectFailed(errCode: number, errMsg: string): void;
  onKickedOffline(): void;
  onUserTokenExpired(): void;
  onUserTokenInvalid(errMsg: string): void;
}

/**
 * 消息监听器接口
 */
export interface MsgListener {
  onRecvNewMessage(message: string): void;
  onRecvC2CReadReceipt(msgReceiptList: string): void;
  onNewRecvMessageRevoked(messageRevoked: string): void;
  onRecvOfflineNewMessage(message: string): void;
  onMsgDeleted(message: string): void;
  onRecvOnlineOnlyMessage(message: string): void;
}

/**
 * 会话监听器接口
 */
export interface ConvListener {
  onSyncServerStart(reinstalled: boolean): void;
  onSyncServerFinish(reinstalled: boolean): void;
  onSyncServerProgress(progress: number): void;
  onSyncServerFailed(reinstalled: boolean): void;
  onNewConversation(conversationList: string): void;
  onConversationChanged(conversationList: string): void;
  onTotalUnreadMessageCountChanged(totalUnreadCount: number): void;
  onConversationUserInputStatusChanged(change: string): void;
}

/**
 * 群组监听器接口
 */
export interface GroupListener {
  onJoinedGroupAdded(groupInfo: string): void;
  onJoinedGroupDeleted(groupInfo: string): void;
  onGroupMemberAdded(groupMemberInfo: string): void;
  onGroupMemberDeleted(groupMemberInfo: string): void;
  onGroupApplicationAdded(groupApplication: string): void;
  onGroupApplicationDeleted(groupApplication: string): void;
  onGroupInfoChanged(groupInfo: string): void;
  onGroupDismissed(groupInfo: string): void;
  onGroupMemberInfoChanged(groupMemberInfo: string): void;
  onGroupApplicationAccepted(groupApplication: string): void;
  onGroupApplicationRejected(groupApplication: string): void;
}

/**
 * 好友监听器接口
 */
export interface FriendListener {
  onFriendApplicationAdded(friendApplication: string): void;
  onFriendApplicationDeleted(friendApplication: string): void;
  onFriendApplicationAccepted(friendApplication: string): void;
  onFriendApplicationRejected(friendApplication: string): void;
  onFriendAdded(friendInfo: string): void;
  onFriendDeleted(friendInfo: string): void;
  onFriendInfoChanged(friendInfo: string): void;
  onBlackAdded(blackInfo: string): void;
  onBlackDeleted(blackInfo: string): void;
}

/**
 * 用户监听器接口
 */
export interface UserListener {
  onSelfInfoUpdated(userInfo: string): void;
  onUserStatusChanged(userOnlineStatus: string): void;
}

/**
 * 信令监听器接口
 */
export interface SignalingListener {
  onReceiveNewInvitation(receiveNewInvitationCallback: string): void;
  onInviteeAccepted(inviteeAcceptedCallback: string): void;
  onInviteeAcceptedByOtherDevice(inviteeAcceptedCallback: string): void;
  onInviteeRejected(inviteeRejectedCallback: string): void;
  onInviteeRejectedByOtherDevice(inviteeRejectedCallback: string): void;
  onInvitationCancelled(invitationCancelledCallback: string): void;
  onInvitationTimeout(invitationTimeoutCallback: string): void;
  onHangUp(hangUpCallback: string): void;
  onRoomParticipantConnected(onRoomParticipantConnectedCallback: string): void;
  onRoomParticipantDisconnected(onRoomParticipantDisconnectedCallback: string): void;
}

/**
 * 自定义业务监听器接口
 */
export interface CustomBusinessListener {
  onRecvCustomBusinessMessage(businessMessage: string): void;
}

/**
 * 消息KV信息监听器接口
 */
export interface MsgKvInfoListener {
  onMessageKvInfoChanged(messageChangedList: string): void;
}

// ============================================================
// 初始化与登录
// ============================================================

/**
 * 初始化 SDK
 * @param connectListener 连接监听器
 * @param operationID 唯一操作标识
 * @param config 配置参数 (JSON 字符串)
 * @returns 是否初始化成功
 */
export function initSdk(connectListener: ConnListener, operationID: string, config: string): number;

/**
 * 登录
 * @param baseCallback 基础回调
 * @param operationID 唯一操作标识
 * @param userID 用户 ID
 * @param token 登录令牌
 */
export function login(baseCallback: BaseCallback, operationID: string, userID: string, token: string): void;

/**
 * 登出
 * @param baseCallback 基础回调
 * @param operationID 唯一操作标识
 */
export function logout(baseCallback: BaseCallback, operationID: string): void;

/**
 * 获取登录状态
 * @param operationID 唯一操作标识
 * @returns 登录状态码
 */
export function getLoginStatus(operationID: string): number;

/**
 * 获取当前登录用户 ID
 * @returns 用户 ID
 */
export function getLoginUserID(): string;

/**
 * 上传文件
 * @param baseCallback 基础回调
 * @param operationID 唯一操作标识
 * @param reqData 请求参数 (JSON 字符串)
 * @param uploadFileCallback 上传文件回调
 */
export function uploadFile(baseCallback: BaseCallback, operationID: string, reqData: string, uploadFileCallback: UploadFileCallback): void;

// ============================================================
// 用户
// ============================================================

/**
 * 设置用户监听器
 * @param userListener 用户监听器
 */
export function setUserListener(userListener: UserListener): void;

/**
 * 设置自定义业务监听器
 * @param customBusinessListener 自定义业务监听器
 */
export function setCustomBusinessListener(customBusinessListener: CustomBusinessListener): void;

/**
 * 设置消息kv信息监听器
 * @param msgKvInfoListener 消息kv信息监听器
 */
export function setMessageKvInfoListener(msgKvInfoListener: MsgKvInfoListener): void;

/**
 * 获取用户信息
 * @param baseCallback 基础回调
 * @param operationID 唯一操作标识
 * @param userIDList 用户 ID 列表 (JSON 字符串数组)
 */
export function getUsersInfo(baseCallback: BaseCallback, operationID: string, userIDList: string): void;

/**
 * 获取当前用户信息
 * @param baseCallback 基础回调
 * @param operationID 唯一操作标识
 */
export function getSelfUserInfo(baseCallback: BaseCallback, operationID: string): void;

/**
 * 设置当前用户信息
 * @param baseCallback 基础回调
 * @param operationID 唯一操作标识
 * @param userInfo 用户信息 (JSON 字符串)
 */
export function setSelfInfo(baseCallback: BaseCallback, operationID: string, userInfo: string): void;

/**
 * 获取用户在线状态
 * @param baseCallback 基础回调
 * @param operationID 唯一操作标识
 * @param userIDList 用户 ID 列表 (JSON 字符串数组)
 */
export function getUserStatus(baseCallback: BaseCallback, operationID: string, userIDList: string): void;

/**
 * 订阅用户状态
 * @param baseCallback 基础回调
 * @param operationID 唯一操作标识
 * @param userIDList 用户 ID 列表 (JSON 字符串数组)
 */
export function subscribeUsersStatus(baseCallback: BaseCallback, operationID: string, userIDList: string): void;

/**
 * 取消订阅用户状态
 * @param baseCallback 基础回调
 * @param operationID 唯一操作标识
 * @param userIDList 用户 ID 列表 (JSON 字符串数组)
 */
export function unsubscribeUsersStatus(baseCallback: BaseCallback, operationID: string, userIDList: string): void;

/**
 * 获取已订阅的用户状态
 * @param baseCallback 基础回调
 * @param operationID 唯一操作标识
 */
export function getSubscribeUsersStatus(baseCallback: BaseCallback, operationID: string): void;

/**
 * 设置应用后台状态
 * @param baseCallback 基础回调
 * @param operationID 唯一操作标识
 * @param isBackground 是否在后台
 */
export function setAppBackgroundStatus(baseCallback: BaseCallback, operationID: string, isBackground: boolean): void;

/**
 * 网络状态变化
 * @param baseCallback 基础回调
 * @param operationID 唯一操作标识
 */
export function networkStatusChanged(baseCallback: BaseCallback, operationID: string): void;

// ============================================================
// 会话
// ============================================================

/**
 * 设置会话监听器
 * @param convListener 会话监听器
 */
export function setConversationListener(convListener: ConvListener): void;

/**
 * 获取所有会话列表
 * @param baseCallback 基础回调
 * @param operationID 唯一操作标识
 */
export function getAllConversationList(baseCallback: BaseCallback, operationID: string): void;

/**
 * 分页获取会话列表
 * @param baseCallback 基础回调
 * @param operationID 唯一操作标识
 * @param offset 偏移量
 * @param count 数量
 */
export function getConversationListSplit(baseCallback: BaseCallback, operationID: string, offset: number, count: number): void;

/**
 * 获取单个会话
 * @param baseCallback 基础回调
 * @param operationID 唯一操作标识
 * @param sessionType 会话类型
 * @param sourceID 源 ID
 */
export function getOneConversation(baseCallback: BaseCallback, operationID: string, sessionType: number, sourceID: string): void;

/**
 * 获取多个会话
 * @param baseCallback 基础回调
 * @param operationID 唯一操作标识
 * @param conversationIDList 会话 ID 列表 (JSON 字符串数组)
 */
export function getMultipleConversation(baseCallback: BaseCallback, operationID: string, conversationIDList: string): void;

/**
 * 根据会话类型获取会话 ID
 * @param operationID 唯一操作标识
 * @param sourceID 源 ID
 * @param sessionType 会话类型
 * @returns 会话 ID
 */
export function getConversationIDBySessionType(operationID: string, sourceID: string, sessionType: number): string;

/**
 * 获取未读消息总数
 * @param baseCallback 基础回调
 * @param operationID 唯一操作标识
 */
export function getTotalUnreadMsgCount(baseCallback: BaseCallback, operationID: string): void;

/**
 * 标记会话消息已读
 * @param baseCallback 基础回调
 * @param operationID 唯一操作标识
 * @param conversationID 会话 ID
 */
export function markConversationMessageAsRead(baseCallback: BaseCallback, operationID: string, conversationID: string): void;

/**
 * 设置会话属性
 * @param baseCallback 基础回调
 * @param operationID 唯一操作标识
 * @param conversationID 会话 ID
 * @param params 参数 (JSON 字符串)
 */
export function setConversation(baseCallback: BaseCallback, operationID: string, conversationID: string, params: string): void;

/**
 * 设置会话草稿
 * @param baseCallback 基础回调
 * @param operationID 唯一操作标识
 * @param conversationID 会话 ID
 * @param draftText 草稿文本
 */
export function setConversationDraft(baseCallback: BaseCallback, operationID: string, conversationID: string, draftText: string): void;

/**
 * 置顶/取消置顶会话
 * @param baseCallback 基础回调
 * @param operationID 唯一操作标识
 * @param conversationID 会话 ID
 * @param isPinned 是否置顶
 */
export function pinConversation(baseCallback: BaseCallback, operationID: string, conversationID: string, isPinned: boolean): void;

/**
 * 设置会话消息接收选项
 * @param baseCallback 基础回调
 * @param operationID 唯一操作标识
 * @param conversationID 会话 ID
 * @param opt 接收选项
 */
export function setConversationRecvMessageOpt(baseCallback: BaseCallback, operationID: string, conversationID: string, opt: number): void;

/**
 * 设置会话私密聊天
 * @param baseCallback 基础回调
 * @param operationID 唯一操作标识
 * @param conversationID 会话 ID
 * @param isPrivate 是否私密
 */
export function setConversationPrivateChat(baseCallback: BaseCallback, operationID: string, conversationID: string, isPrivate: boolean): void;

/**
 * 设置会话阅后即焚时长
 * @param baseCallback 基础回调
 * @param operationID 唯一操作标识
 * @param conversationID 会话 ID
 * @param burnDuration 销毁时长（秒）
 */
export function setConversationBurnDuration(baseCallback: BaseCallback, operationID: string, conversationID: string, burnDuration: number): void;

/**
 * 重置会话@提醒类型
 * @param baseCallback 基础回调
 * @param operationID 唯一操作标识
 * @param conversationID 会话 ID
 */
export function resetConversationGroupAtType(baseCallback: BaseCallback, operationID: string, conversationID: string): void;

/**
 * 隐藏会话
 * @param baseCallback 基础回调
 * @param operationID 唯一操作标识
 * @param conversationID 会话 ID
 */
export function hideConversation(baseCallback: BaseCallback, operationID: string, conversationID: string): void;

/**
 * 隐藏所有会话
 * @param baseCallback 基础回调
 * @param operationID 唯一操作标识
 */
export function hideAllConversations(baseCallback: BaseCallback, operationID: string): void;

/**
 * 清除会话并删除所有消息
 * @param baseCallback 基础回调
 * @param operationID 唯一操作标识
 * @param conversationID 会话 ID
 */
export function clearConversationAndDeleteAllMsg(baseCallback: BaseCallback, operationID: string, conversationID: string): void;

/**
 * 删除会话并删除所有消息
 * @param baseCallback 基础回调
 * @param operationID 唯一操作标识
 * @param conversationID 会话 ID
 */
export function deleteConversationAndDeleteAllMsg(baseCallback: BaseCallback, operationID: string, conversationID: string): void;

// ============================================================
// 消息
// ============================================================

/**
 * 设置高级消息监听器
 * @param msgListener 消息监听器
 */
export function setAdvancedMsgListener(msgListener: MsgListener): void;

/**
 * 设置批量消息监听器
 * @param msgListener 消息监听器
 */
export function setBatchMsgListener(msgListener: MsgListener): void;

/**
 * 设置信令监听器
 * @param signalingListener 信令监听器
 */
export function setSignalingListener(signalingListener: SignalingListener): void;

/**
 * 创建文本消息
 * @param operationID 唯一操作标识
 * @param text 文本内容
 * @returns 消息对象 (JSON 字符串)
 */
export function createTextMessage(operationID: string, text: string): string;

/**
 * 从本地路径创建图片消息
 * @param operationID 唯一操作标识
 * @param imagePath 图片路径
 * @returns 消息对象 (JSON 字符串)
 */
export function createImageMessage(operationID: string, imagePath: string): string;

/**
 * 从本地路径创建语音消息
 * @param operationID 唯一操作标识
 * @param soundPath 语音路径
 * @param duration 时长（秒）
 * @returns 消息对象 (JSON 字符串)
 */
export function createSoundMessage(operationID: string, soundPath: string, duration: number): string;

/**
 * 从本地路径创建文件消息
 * @param operationID 唯一操作标识
 * @param filePath 文件路径
 * @param fileName 文件名
 * @returns 消息对象 (JSON 字符串)
 */
export function createFileMessage(operationID: string, filePath: string, fileName: string): string;

/**
 * 从本地路径创建视频消息
 * @param operationID 唯一操作标识
 * @param videoPath 视频路径
 * @param videoType 视频类型
 * @param duration 时长（秒）
 * @param snapshotPath 缩略图路径
 * @returns 消息对象 (JSON 字符串)
 */
export function createVideoMessage(operationID: string, videoPath: string, videoType: string, duration: number, snapshotPath: string): string;

/**
 * 创建@消息
 * @param operationID 唯一操作标识
 * @param text 文本内容
 * @param atUserIDList @用户 ID 列表 (JSON 字符串数组)
 * @param atUsersInfo @用户信息 (可选，JSON 字符串)
 * @param quoteMessage 引用消息 (可选，JSON 字符串)
 * @returns 消息对象 (JSON 字符串)
 */
export function createTextAtMessage(operationID: string, text: string, atUserIDList: string, atUsersInfo: string | null, quoteMessage: string | null): string;

/**
 * 创建引用消息
 * @param operationID 唯一操作标识
 * @param text 文本内容
 * @param quoteMessage 引用消息 (JSON 字符串)
 * @returns 消息对象 (JSON 字符串)
 */
export function createQuoteMessage(operationID: string, text: string, quoteMessage: string): string;

/**
 * 创建卡片消息
 * @param operationID 唯一操作标识
 * @param params 卡片参数 (JSON 字符串)
 * @returns 消息对象 (JSON 字符串)
 */
export function createCardMessage(operationID: string, params: string): string;

/**
 * 从本地路径创建图片消息
 * @param operationID 唯一操作标识
 * @param imagePath 图片路径
 * @returns 消息对象 (JSON 字符串)
 */
export function createImageMessageFromFullPath(operationID: string, imagePath: string): string;

/**
 * 从 URL 创建图片消息
 * @param operationID 唯一操作标识
 * @param sourcePath 源路径
 * @param sourcePicture 源图片信息 (JSON 字符串)
 * @param bigPicture 大图信息 (JSON 字符串)
 * @param snapshotPicture 缩略图信息 (JSON 字符串)
 * @returns 消息对象 (JSON 字符串)
 */
export function createImageMessageByURL(operationID: string, sourcePath: string, sourcePicture: string, bigPicture: string, snapshotPicture: string): string;

/**
 * 从本地路径创建语音消息
 * @param operationID 唯一操作标识
 * @param soundPath 语音路径
 * @param duration 时长（秒）
 * @returns 消息对象 (JSON 字符串)
 */
export function createSoundMessageFromFullPath(operationID: string, soundPath: string, duration: number): string;

/**
 * 从 URL 创建语音消息
 * @param operationID 唯一操作标识
 * @param params 参数 (JSON 字符串)
 * @returns 消息对象 (JSON 字符串)
 */
export function createSoundMessageByURL(operationID: string, params: string): string;

/**
 * 从本地路径创建视频消息
 * @param operationID 唯一操作标识
 * @param videoPath 视频路径
 * @param videoType 视频类型
 * @param duration 时长（秒）
 * @param snapshotPath 缩略图路径
 * @returns 消息对象 (JSON 字符串)
 */
export function createVideoMessageFromFullPath(operationID: string, videoPath: string, videoType: string, duration: number, snapshotPath: string): string;

/**
 * 从 URL 创建视频消息
 * @param operationID 唯一操作标识
 * @param params 参数 (JSON 字符串)
 * @returns 消息对象 (JSON 字符串)
 */
export function createVideoMessageByURL(operationID: string, params: string): string;

/**
 * 从本地路径创建文件消息
 * @param operationID 唯一操作标识
 * @param filePath 文件路径
 * @param fileName 文件名
 * @returns 消息对象 (JSON 字符串)
 */
export function createFileMessageFromFullPath(operationID: string, filePath: string, fileName: string): string;

/**
 * 从 URL 创建文件消息
 * @param operationID 唯一操作标识
 * @param params 参数 (JSON 字符串)
 * @returns 消息对象 (JSON 字符串)
 */
export function createFileMessageByURL(operationID: string, params: string): string;

/**
 * 创建合并消息
 * @param operationID 唯一操作标识
 * @param messageList 消息列表 (JSON 字符串数组)
 * @param title 标题
 * @param summaryList 摘要列表 (JSON 字符串数组)
 * @returns 消息对象 (JSON 字符串)
 */
export function createMergerMessage(operationID: string, messageList: string, title: string, summaryList: string): string;

/**
 * 创建转发消息
 * @param operationID 唯一操作标识
 * @param params 参数 (JSON 字符串)
 * @returns 消息对象 (JSON 字符串)
 */
export function createForwardMessage(operationID: string, params: string): string;

/**
 * 创建位置消息
 * @param operationID 唯一操作标识
 * @param description 描述
 * @param longitude 经度
 * @param latitude 纬度
 * @returns 消息对象 (JSON 字符串)
 */
export function createLocationMessage(operationID: string, description: string, longitude: number, latitude: number): string;

/**
 * 创建自定义消息
 * @param operationID 唯一操作标识
 * @param data 自定义数据
 * @param extension 扩展数据
 * @param description 描述
 * @returns 消息对象 (JSON 字符串)
 */
export function createCustomMessage(operationID: string, data: string, extension: string, description: string): string;

/**
 * 创建表情消息
 * @param operationID 唯一操作标识
 * @param index 表情索引
 * @param data 表情数据
 * @returns 消息对象 (JSON 字符串)
 */
export function createFaceMessage(operationID: string, index: number, data: string): string;

/**
 * 发送消息
 * @param sendMsgCallBack 发送消息回调
 * @param operationID 唯一操作标识
 * @param message 消息内容 (JSON 字符串)
 * @param recvID 接收者 ID
 * @param groupID 群组 ID
 * @param offlinePushInfo 离线推送信息 (JSON 字符串)
 * @param isOnlineOnly 是否仅在线发送
 */
export function sendMessage(sendMsgCallBack: SendMsgCallBack, operationID: string, message: string, recvID: string, groupID: string, offlinePushInfo: string, isOnlineOnly: boolean): void;

/**
 * 发送消息（不通过 OSS）
 * @param sendMsgCallBack 发送消息回调
 * @param operationID 唯一操作标识
 * @param message 消息内容 (JSON 字符串)
 * @param receiver 接收者 ID
 * @param groupID 群组 ID
 * @param offlinePushInfo 离线推送信息 (JSON 字符串)
 * @param isOnlineOnly 是否仅在线发送
 */
export function sendMessageNotOss(sendMsgCallBack: SendMsgCallBack, operationID: string, message: string, receiver: string, groupID: string, offlinePushInfo: string, isOnlineOnly: boolean): void;

/**
 * 更新输入状态
 * @param baseCallback 基础回调
 * @param operationID 唯一操作标识
 * @param recvID 接收者 ID
 * @param msgTip 消息提示
 */
export function typingStatusUpdate(baseCallback: BaseCallback, operationID: string, recvID: string, msgTip: string): void;

/**
 * 更改输入状态
 * @param baseCallback 基础回调
 * @param operationID 唯一操作标识
 * @param conversationID 会话 ID
 * @param focus 是否获取焦点
 */
export function changeInputStates(baseCallback: BaseCallback, operationID: string, conversationID: string, focus: boolean): void;

/**
 * 获取输入状态
 * @param baseCallback 基础回调
 * @param operationID 唯一操作标识
 * @param conversationID 会话 ID
 * @param userID 用户 ID
 */
export function getInputStates(baseCallback: BaseCallback, operationID: string, conversationID: string, userID: string): void;

/**
 * 撤回消息
 * @param baseCallback 基础回调
 * @param operationID 唯一操作标识
 * @param conversationID 会话 ID
 * @param clientMsgID 客户端消息 ID
 */
export function revokeMessage(baseCallback: BaseCallback, operationID: string, conversationID: string, clientMsgID: string): void;

/**
 * 删除消息
 * @param baseCallback 基础回调
 * @param operationID 唯一操作标识
 * @param conversationID 会话 ID
 * @param clientMsgID 客户端消息 ID
 */
export function deleteMessage(baseCallback: BaseCallback, operationID: string, conversationID: string, clientMsgID: string): void;

/**
 * 从本地存储删除消息
 * @param baseCallback 基础回调
 * @param operationID 唯一操作标识
 * @param conversationID 会话 ID
 * @param clientMsgID 客户端消息 ID
 */
export function deleteMessageFromLocalStorage(baseCallback: BaseCallback, operationID: string, conversationID: string, clientMsgID: string): void;

/**
 * 根据消息ID标记消息已读
 * @param baseCallback 基础回调
 * @param operationID 唯一操作标识
 * @param conversationID 会话 ID
 * @param clientMsgIDs 客户端消息 ID 列表（逗号分隔）
 */
export function markMessagesAsReadByMsgID(baseCallback: BaseCallback, operationID: string, conversationID: string, clientMsgIDs: string): void;

/**
 * 删除本地所有消息
 * @param baseCallback 基础回调
 * @param operationID 唯一操作标识
 */
export function deleteAllMsgFromLocal(baseCallback: BaseCallback, operationID: string): void;

/**
 * 删除本地和服务器所有消息
 * @param baseCallback 基础回调
 * @param operationID 唯一操作标识
 */
export function deleteAllMsgFromLocalAndSvr(baseCallback: BaseCallback, operationID: string): void;

/**
 * 搜索本地消息
 * @param baseCallback 基础回调
 * @param operationID 唯一操作标识
 * @param params 搜索参数 (JSON 字符串)
 */
export function searchLocalMessages(baseCallback: BaseCallback, operationID: string, params: string): void;

/**
 * 获取高级历史消息列表
 * @param baseCallback 基础回调
 * @param operationID 唯一操作标识
 * @param params 查询参数 (JSON 字符串)
 */
export function getAdvancedHistoryMessageList(baseCallback: BaseCallback, operationID: string, params: string): void;

/**
 * 反向获取高级历史消息列表
 * @param baseCallback 基础回调
 * @param operationID 唯一操作标识
 * @param params 查询参数 (JSON 字符串)
 */
export function getAdvancedHistoryMessageListReverse(baseCallback: BaseCallback, operationID: string, params: string): void;

/**
 * 查找消息列表
 * @param baseCallback 基础回调
 * @param operationID 唯一操作标识
 * @param params 查询参数 (JSON 字符串)
 */
export function findMessageList(baseCallback: BaseCallback, operationID: string, params: string): void;

/**
 * 插入单聊消息到本地存储
 * @param baseCallback 基础回调
 * @param operationID 唯一操作标识
 * @param message 消息内容 (JSON 字符串)
 * @param recvID 接收者 ID
 * @param sendID 发送者 ID
 */
export function insertSingleMessageToLocalStorage(baseCallback: BaseCallback, operationID: string, message: string, recvID: string, sendID: string): void;

/**
 * 插入群聊消息到本地存储
 * @param baseCallback 基础回调
 * @param operationID 唯一操作标识
 * @param message 消息内容 (JSON 字符串)
 * @param groupID 群组 ID
 * @param sendID 发送者 ID
 */
export function insertGroupMessageToLocalStorage(baseCallback: BaseCallback, operationID: string, message: string, groupID: string, sendID: string): void;

/**
 * 设置消息本地扩展信息
 * @param baseCallback 基础回调
 * @param operationID 唯一操作标识
 * @param conversationID 会话 ID
 * @param clientMsgID 客户端消息 ID
 * @param localEx 本地扩展数据
 */
export function setMessageLocalEx(baseCallback: BaseCallback, operationID: string, conversationID: string, clientMsgID: string, localEx: string): void;

// ============================================================
// 好友
// ============================================================

/**
 * 设置好友监听器
 * @param friendListener 好友监听器
 */
export function setFriendListener(friendListener: FriendListener): void;

/**
 * 获取好友列表
 * @param baseCallback 基础回调
 * @param operationID 唯一操作标识
 * @param filterBlack 是否过滤黑名单
 */
export function getFriendList(baseCallback: BaseCallback, operationID: string, filterBlack: boolean): void;

/**
 * 分页获取好友列表
 * @param baseCallback 基础回调
 * @param operationID 唯一操作标识
 * @param offset 偏移量
 * @param count 数量
 * @param filterBlack 是否过滤黑名单
 */
export function getFriendListPage(baseCallback: BaseCallback, operationID: string, offset: number, count: number, filterBlack: boolean): void;

/**
 * 获取指定好友信息
 * @param baseCallback 基础回调
 * @param operationID 唯一操作标识
 * @param userIDList 用户 ID 列表 (JSON 字符串数组)
 * @param ex 扩展字段
 */
export function getSpecifiedFriendsInfo(baseCallback: BaseCallback, operationID: string, userIDList: string, ex: boolean): void;

/**
 * 搜索好友
 * @param baseCallback 基础回调
 * @param operationID 唯一操作标识
 * @param params 搜索参数 (JSON 字符串)
 */
export function searchFriends(baseCallback: BaseCallback, operationID: string, params: string): void;

/**
 * 添加好友
 * @param baseCallback 基础回调
 * @param operationID 唯一操作标识
 * @param params 参数 (JSON 字符串)
 */
export function addFriend(baseCallback: BaseCallback, operationID: string, params: string): void;

/**
 * 检查好友关系
 * @param baseCallback 基础回调
 * @param operationID 唯一操作标识
 * @param params 参数 (JSON 字符串数组)
 */
export function checkFriend(baseCallback: BaseCallback, operationID: string, params: string): void;

/**
 * 更新好友信息
 * @param baseCallback 基础回调
 * @param operationID 唯一操作标识
 * @param params 参数 (JSON 字符串)
 */
export function updateFriends(baseCallback: BaseCallback, operationID: string, params: string): void;

/**
 * 获取未处理好友申请数量
 * @param baseCallback 基础回调
 * @param operationID 唯一操作标识
 * @param params 参数 (JSON 字符串)
 */
export function getFriendApplicationUnhandledCount(baseCallback: BaseCallback, operationID: string, params: string): void;

/**
 * 删除好友
 * @param baseCallback 基础回调
 * @param operationID 唯一操作标识
 * @param friendUserID 好友用户 ID
 */
export function deleteFriend(baseCallback: BaseCallback, operationID: string, friendUserID: string): void;

/**
 * 设置好友备注
 * @param baseCallback 基础回调
 * @param operationID 唯一操作标识
 * @param toUserID 用户 ID
 * @param remark 备注
 */
export function setFriendRemark(baseCallback: BaseCallback, operationID: string, toUserID: string, remark: string): void;

/**
 * 获取作为申请人的好友申请列表
 * @param baseCallback 基础回调
 * @param operationID 唯一操作标识
 * @param params 参数 (JSON 字符串)
 */
export function getFriendApplicationListAsApplicant(baseCallback: BaseCallback, operationID: string, params: string): void;

/**
 * 获取作为接收人的好友申请列表
 * @param baseCallback 基础回调
 * @param operationID 唯一操作标识
 * @param params 参数 (JSON 字符串)
 */
export function getFriendApplicationListAsRecipient(baseCallback: BaseCallback, operationID: string, params: string): void;

/**
 * 接受好友申请
 * @param baseCallback 基础回调
 * @param operationID 唯一操作标识
 * @param params 参数 (JSON 字符串)
 */
export function acceptFriendApplication(baseCallback: BaseCallback, operationID: string, params: string): void;

/**
 * 拒绝好友申请
 * @param baseCallback 基础回调
 * @param operationID 唯一操作标识
 * @param params 参数 (JSON 字符串)
 */
export function refuseFriendApplication(baseCallback: BaseCallback, operationID: string, params: string): void;

/**
 * 添加黑名单
 * @param baseCallback 基础回调
 * @param operationID 唯一操作标识
 * @param toUserID 用户 ID
 * @param ex 扩展字段
 */
export function addBlack(baseCallback: BaseCallback, operationID: string, toUserID: string, ex: string): void;

/**
 * 获取黑名单
 * @param baseCallback 基础回调
 * @param operationID 唯一操作标识
 */
export function getBlackList(baseCallback: BaseCallback, operationID: string): void;

/**
 * 移除黑名单
 * @param baseCallback 基础回调
 * @param operationID 唯一操作标识
 * @param userID 用户 ID
 */
export function removeBlack(baseCallback: BaseCallback, operationID: string, userID: string): void;

// ============================================================
// 群组
// ============================================================

/**
 * 设置群组监听器
 * @param groupListener 群组监听器
 */
export function setGroupListener(groupListener: GroupListener): void;

/**
 * 创建群组
 * @param baseCallback 基础回调
 * @param operationID 唯一操作标识
 * @param params 参数 (JSON 字符串)
 */
export function createGroup(baseCallback: BaseCallback, operationID: string, params: string): void;

/**
 * 加入群组
 * @param baseCallback 基础回调
 * @param operationID 唯一操作标识
 * @param groupID 群组 ID
 * @param reqMsg 申请消息
 * @param joinSource 加入来源
 * @param ex 扩展字段
 */
export function joinGroup(baseCallback: BaseCallback, operationID: string, groupID: string, reqMsg: string, joinSource: number, ex: string): void;

/**
 * 退出群组
 * @param baseCallback 基础回调
 * @param operationID 唯一操作标识
 * @param groupID 群组 ID
 */
export function quitGroup(baseCallback: BaseCallback, operationID: string, groupID: string): void;

/**
 * 解散群组
 * @param baseCallback 基础回调
 * @param operationID 唯一操作标识
 * @param groupID 群组 ID
 */
export function dismissGroup(baseCallback: BaseCallback, operationID: string, groupID: string): void;

/**
 * 获取已加入的群组列表
 * @param baseCallback 基础回调
 * @param operationID 唯一操作标识
 */
export function getJoinedGroupList(baseCallback: BaseCallback, operationID: string): void;

/**
 * 分页获取已加入的群组列表
 * @param baseCallback 基础回调
 * @param operationID 唯一操作标识
 * @param offset 偏移量
 * @param count 数量
 */
export function getJoinedGroupListPage(baseCallback: BaseCallback, operationID: string, offset: number, count: number): void;

/**
 * 获取指定群组信息
 * @param baseCallback 基础回调
 * @param operationID 唯一操作标识
 * @param params 群组 ID 列表 (JSON 字符串数组)
 */
export function getSpecifiedGroupsInfo(baseCallback: BaseCallback, operationID: string, params: string): void;

/**
 * 获取群成员列表
 * @param baseCallback 基础回调
 * @param operationID 唯一操作标识
 * @param groupID 群组 ID
 * @param filter 过滤类型
 * @param offset 偏移量
 * @param count 数量
 */
export function getGroupMemberList(baseCallback: BaseCallback, operationID: string, groupID: string, filter: number, offset: number, count: number): void;

/**
 * 获取群主和管理员
 * @param baseCallback 基础回调
 * @param operationID 唯一操作标识
 * @param groupID 群组 ID
 */
export function getGroupMemberOwnerAndAdmin(baseCallback: BaseCallback, operationID: string, groupID: string): void;

/**
 * 获取指定群成员信息
 * @param baseCallback 基础回调
 * @param operationID 唯一操作标识
 * @param groupID 群组 ID
 * @param userIDList 用户 ID 列表 (JSON 字符串数组)
 */
export function getSpecifiedGroupMembersInfo(baseCallback: BaseCallback, operationID: string, groupID: string, userIDList: string): void;

/**
 * 获取群内指定用户
 * @param baseCallback 基础回调
 * @param operationID 唯一操作标识
 * @param groupID 群组 ID
 * @param userIDList 用户 ID 列表 (JSON 字符串数组)
 */
export function getUsersInGroup(baseCallback: BaseCallback, operationID: string, groupID: string, userIDList: string): void;

/**
 * 搜索群成员
 * @param baseCallback 基础回调
 * @param operationID 唯一操作标识
 * @param params 搜索参数 (JSON 字符串)
 */
export function searchGroupMembers(baseCallback: BaseCallback, operationID: string, params: string): void;

/**
 * 设置群组信息
 * @param baseCallback 基础回调
 * @param operationID 唯一操作标识
 * @param params 参数 (JSON 字符串)
 */
export function setGroupInfo(baseCallback: BaseCallback, operationID: string, params: string): void;

/**
 * 更改群组禁言状态
 * @param baseCallback 基础回调
 * @param operationID 唯一操作标识
 * @param groupID 群组 ID
 * @param isMute 是否禁言
 */
export function changeGroupMute(baseCallback: BaseCallback, operationID: string, groupID: string, isMute: boolean): void;

/**
 * 更改群成员禁言状态
 * @param baseCallback 基础回调
 * @param operationID 唯一操作标识
 * @param groupID 群组 ID
 * @param userID 用户 ID
 * @param mutedSeconds 禁言时长（秒）
 */
export function changeGroupMemberMute(baseCallback: BaseCallback, operationID: string, groupID: string, userID: string, mutedSeconds: number): void;

/**
 * 设置群成员信息
 * @param baseCallback 基础回调
 * @param operationID 唯一操作标识
 * @param params 参数 (JSON 字符串)
 */
export function setGroupMemberInfo(baseCallback: BaseCallback, operationID: string, params: string): void;

/**
 * 邀请用户入群
 * @param baseCallback 基础回调
 * @param operationID 唯一操作标识
 * @param groupID 群组 ID
 * @param userIDList 用户 ID 列表 (JSON 字符串数组)
 * @param reason 原因
 */
export function inviteUserToGroup(baseCallback: BaseCallback, operationID: string, groupID: string, userIDList: string, reason: string): void;

/**
 * 踢出群成员
 * @param baseCallback 基础回调
 * @param operationID 唯一操作标识
 * @param groupID 群组 ID
 * @param userIDList 用户 ID 列表 (JSON 字符串数组)
 * @param reason 原因
 */
export function kickGroupMember(baseCallback: BaseCallback, operationID: string, groupID: string, userIDList: string, reason: string): void;

/**
 * 转让群主
 * @param baseCallback 基础回调
 * @param operationID 唯一操作标识
 * @param groupID 群组 ID
 * @param newOwnerUserID 新群主用户 ID
 */
export function transferGroupOwner(baseCallback: BaseCallback, operationID: string, groupID: string, newOwnerUserID: string): void;

/**
 * 获取作为申请人的群申请列表
 * @param baseCallback 基础回调
 * @param operationID 唯一操作标识
 * @param params 参数 (JSON 字符串)
 */
export function getGroupApplicationListAsApplicant(baseCallback: BaseCallback, operationID: string, params: string): void;

/**
 * 获取作为接收人的群申请列表
 * @param baseCallback 基础回调
 * @param operationID 唯一操作标识
 * @param params 参数 (JSON 字符串)
 */
export function getGroupApplicationListAsRecipient(baseCallback: BaseCallback, operationID: string, params: string): void;

/**
 * 获取未处理群申请数量
 * @param baseCallback 基础回调
 * @param operationID 唯一操作标识
 * @param params 参数 (JSON 字符串)
 */
export function getGroupApplicationUnhandledCount(baseCallback: BaseCallback, operationID: string, params: string): void;

/**
 * 接受群申请
 * @param baseCallback 基础回调
 * @param operationID 唯一操作标识
 * @param groupID 群组 ID
 * @param userID 用户 ID
 * @param handleMsg 处理消息
 */
export function acceptGroupApplication(baseCallback: BaseCallback, operationID: string, groupID: string, userID: string, handleMsg: string): void;

/**
 * 拒绝群申请
 * @param baseCallback 基础回调
 * @param operationID 唯一操作标识
 * @param groupID 群组 ID
 * @param userID 用户 ID
 * @param handleMsg 处理消息
 */
export function refuseGroupApplication(baseCallback: BaseCallback, operationID: string, groupID: string, userID: string, handleMsg: string): void;

/**
 * 搜索群组
 * @param baseCallback 基础回调
 * @param operationID 唯一操作标识
 * @param params 搜索参数 (JSON 字符串)
 */
export function searchGroups(baseCallback: BaseCallback, operationID: string, params: string): void;

/**
 * 按加入时间过滤获取群成员列表
 * @param baseCallback 基础回调
 * @param operationID 唯一操作标识
 * @param groupID 群组 ID
 * @param offset 偏移量
 * @param count 数量
 * @param joinTimeBegin 加入时间开始
 * @param joinTimeEnd 加入时间结束
 * @param filterUserIDList 过滤用户 ID 列表 (JSON 字符串数组)
 */
export function getGroupMemberListByJoinTimeFilter(baseCallback: BaseCallback, operationID: string, groupID: string, offset: number, count: number, joinTimeBegin: number, joinTimeEnd: number, filterUserIDList: string): void;

/**
 * 检查是否已加入群组
 * @param baseCallback 基础回调
 * @param operationID 唯一操作标识
 * @param groupID 群组 ID
 */
export function isJoinGroup(baseCallback: BaseCallback, operationID: string, groupID: string): void;

// ============================================================
// 工具
// ============================================================

/**
 * 更新 FCM 令牌
 * @param baseCallback 基础回调
 * @param operationID 唯一操作标识
 * @param fcmToken FCM 令牌
 * @param expireTime 过期时间
 */
export function updateFcmToken(baseCallback: BaseCallback, operationID: string, fcmToken: string, expireTime: number): void;

/**
 * 设置应用角标
 * @param baseCallback 基础回调
 * @param operationID 唯一操作标识
 * @param appUnreadCount 未读数量
 */
export function setAppBadge(baseCallback: BaseCallback, operationID: string, appUnreadCount: number): void;

/**
 * 上传日志
 * @param baseCallback 基础回调
 * @param operationID 唯一操作标识
 * @param line 行数
 * @param ex 扩展字段
 * @param uploadLogProgress 上传日志进度回调
 */
export function uploadLogs(baseCallback: BaseCallback, operationID: string, line: number, ex: string, uploadLogProgress: UploadLogProgress): void;

/**
 * 记录日志
 * @param baseCallback 基础回调
 * @param operationID 唯一操作标识
 * @param logLevel 日志级别
 * @param file 文件
 * @param line 行号
 * @param msgs 消息
 * @param err 错误信息
 * @param keyAndValue 键值对 (JSON 字符串数组)
 */
export function logs(baseCallback: BaseCallback, operationID: string, logLevel: number, file: string, line: number, msgs: string, err: string, keyAndValue: string): void;

/**
 * 获取 SDK 版本
 * @returns SDK 版本号
 */
export function getSdkVersion(): string;

/**
 * 反初始化 SDK
 * @param operationID 唯一操作标识
 */
export function unInitSDK(operationID: string): void;

/**
 * 获取@所有人标签
 * @param operationID 唯一操作标识
 * @returns @所有人标签
 */
export function getAtAllTag(operationID: string): string;
