// import { ChatView } from "../chat/ChatView";
// import { MyFriendView } from "../myfriend/MyFriendView";
// import { MyGroupView } from "../mygroup/MyGroupView";
// import { NewFriendView } from "../newfriend/NewFriendView";
// import { NewGroupView } from "../newgroup/NewGroupView";
//
// export class RouterName {
//   static Chat: string = "chat"
//   static NewFriend: string = "new-friend"
//   static NewGroup: string = "new-group"
//   static MyFriend: string = "my-friend"
//   static MyGroup: string = "my-group"
// }
//
// @Builder
// export function RouterMap(name: string) {
//   if (name == RouterName.Chat) {
//    ChatView()
//   } else if (name == RouterName.NewFriend){
//     NewFriendView()
//   } else if (name == RouterName.NewGroup){
//     NewGroupView()
//   } else if (name == RouterName.MyFriend){
//     MyFriendView()
//   } else if (name == RouterName.MyGroup){
//     MyGroupView()
//   }
// }