/* Code generated by cmd/cgo; DO NOT EDIT. */

/* package github.com/openimsdk/openim-sdk-core/v3/native */


#line 1 "cgo-builtin-export-prolog"

#include <stddef.h>

#ifndef GO_CGO_EXPORT_PROLOGUE_H
#define GO_CGO_EXPORT_PROLOGUE_H

#ifndef GO_CGO_GOSTRING_TYPEDEF
typedef struct { const char *p; ptrdiff_t n; } _GoString_;
#endif

#endif

/* Start of preamble from import "C" comments.  */


#line 17 "harmony_bridge.go"

#ifndef LIBOPENIMSDK_H
#define LIBOPENIMSDK_H

#include <stdint.h>
#include <stdlib.h>

// Callback types
typedef void (*ConnNoMsgCb)(int);
typedef void (*ConnWithMsgCb)(int, char*);
typedef void (*InfoCb)(char*);
typedef void (*ReceiptCb)(char*);
typedef void (*DeletedCb)(char*);
typedef void (*SyncBoolCb)(int);
typedef void (*SyncProgressCb)(int);
typedef void (*UnreadCb)(int);

// Callback registry API. Implemented once in harmony_callback_storage.c.
#define CB_MAX 64
typedef void (*SignalingCb)(char*);
typedef void (*CustomBusinessCb)(char*);
typedef void (*MsgKvInfoCb)(char*);
typedef void (*UploadOpenCb)(int, long long);
typedef void (*UploadPartSizeCb)(int, long long, int);
typedef void (*UploadHashProgressCb)(int, int, long long, char*);
typedef void (*UploadHashCompleteCb)(int, char*, char*);
typedef void (*UploadIDCb)(int, char*);
typedef void (*UploadPartCompleteCb)(int, int, long long, char*);
typedef void (*UploadCompleteCb)(int, long long, long long, long long);
typedef void (*UploadFinishCb)(int, long long, char*, int);
typedef void (*UploadLogProgressCb)(int, long long, long long);
typedef void (*SendMsgCb)(int, int);
typedef void (*BaseSuccessCb)(int, char*);
typedef void (*BaseErrorCb)(int, int, char*);

#ifdef __cplusplus
extern "C" {
#endif

int RegisterConnListener(ConnNoMsgCb, ConnNoMsgCb, ConnWithMsgCb, ConnNoMsgCb, ConnNoMsgCb, ConnWithMsgCb);
int RegisterMsgListener(InfoCb, ReceiptCb, InfoCb, InfoCb, DeletedCb, InfoCb);
int RegisterConvListener(SyncBoolCb, SyncBoolCb, SyncProgressCb, SyncBoolCb, InfoCb, InfoCb, UnreadCb, InfoCb);
int RegisterGroupListener(InfoCb, InfoCb, InfoCb, InfoCb, InfoCb, InfoCb, InfoCb, InfoCb, InfoCb, InfoCb, InfoCb);
int RegisterFriendListener(InfoCb, InfoCb, InfoCb, InfoCb, InfoCb, InfoCb, InfoCb, InfoCb, InfoCb);
int RegisterUserListener(InfoCb, InfoCb);
int RegisterSignalingListener(SignalingCb, SignalingCb, SignalingCb, SignalingCb, SignalingCb, SignalingCb, SignalingCb, SignalingCb, SignalingCb, SignalingCb);
int RegisterCustomBusinessListener(CustomBusinessCb);
int RegisterMsgKvInfoListener(MsgKvInfoCb);
int RegisterUploadFileCallback(int, UploadOpenCb, UploadPartSizeCb, UploadHashProgressCb, UploadHashCompleteCb, UploadIDCb, UploadPartCompleteCb, UploadCompleteCb, UploadFinishCb);
int RegisterUploadLogProgress(int, UploadLogProgressCb);
int RegisterBaseCallback(int, BaseSuccessCb, BaseErrorCb);
int RegisterSendMsgCallback(int, SendMsgCb);

void UnregisterConnListener(void);
void UnregisterMsgListener(void);
void UnregisterConvListener(void);
void UnregisterGroupListener(void);
void UnregisterFriendListener(void);
void UnregisterUserListener(void);
void UnregisterSignalingListener(void);
void UnregisterCustomBusinessListener(void);
void UnregisterMsgKvInfoListener(void);
void UnregisterUploadFileCallback(int);
void UnregisterUploadLogProgress(int);
void UnregisterBaseCallback(int);
void UnregisterSendMsgCallback(int);
void UnregisterAllUploadCallbacks(void);
void UnregisterAllListeners(void);

void openim_call_conn_connecting(int);
void openim_call_conn_success(int);
void openim_call_conn_failed(int, char*);
void openim_call_conn_kicked(int);
void openim_call_conn_token_expired(int);
void openim_call_conn_token_invalid(int, char*);
void openim_call_recv_new_msg(char*);
void openim_call_recv_receipt(char*);
void openim_call_msg_revoked(char*);
void openim_call_recv_offline(char*);
void openim_call_msg_deleted(char*);
void openim_call_recv_online(char*);
void openim_call_sync_start(int);
void openim_call_sync_finish(int);
void openim_call_sync_progress(int);
void openim_call_sync_failed(int);
void openim_call_conv_changed(char*);
void openim_call_new_conv(char*);
void openim_call_unread_changed(int);
void openim_call_input_status(char*);
void openim_call_group_joined_add(char*);
void openim_call_group_joined_del(char*);
void openim_call_group_member_add(char*);
void openim_call_group_member_del(char*);
void openim_call_group_app_add(char*);
void openim_call_group_app_del(char*);
void openim_call_group_info_changed(char*);
void openim_call_group_dismissed(char*);
void openim_call_group_member_info(char*);
void openim_call_group_app_accept(char*);
void openim_call_group_app_reject(char*);
void openim_call_friend_app_add(char*);
void openim_call_friend_app_del(char*);
void openim_call_friend_app_accept(char*);
void openim_call_friend_app_reject(char*);
void openim_call_friend_add(char*);
void openim_call_friend_del(char*);
void openim_call_friend_info(char*);
void openim_call_black_add(char*);
void openim_call_black_del(char*);
void openim_call_self_info(char*);
void openim_call_user_status(char*);
void openim_call_signaling_receive_new_invitation(char*);
void openim_call_signaling_invitee_accepted(char*);
void openim_call_signaling_invitee_accepted_other(char*);
void openim_call_signaling_invitee_rejected(char*);
void openim_call_signaling_invitee_rejected_other(char*);
void openim_call_signaling_invitation_cancelled(char*);
void openim_call_signaling_invitation_timeout(char*);
void openim_call_signaling_hangup(char*);
void openim_call_signaling_participant_connected(char*);
void openim_call_signaling_participant_disconnected(char*);
void openim_call_custom_business(char*);
void openim_call_msg_kv_changed(char*);
void openim_call_upload_open(int, long long);
void openim_call_upload_part_size(int, long long, int);
void openim_call_upload_hash_progress(int, int, long long, char*);
void openim_call_upload_hash_complete(int, char*, char*);
void openim_call_upload_id(int, char*);
void openim_call_upload_part_complete(int, int, long long, char*);
void openim_call_upload_complete(int, long long, long long, long long);
void openim_call_upload_finish(int, long long, char*, int);
void openim_call_upload_log_progress(int, long long, long long);
void openim_call_send_msg(int, int);
void openim_call_base_success(int, char*);
void openim_call_base_error(int, int, char*);

#ifdef __cplusplus
}
#endif

#endif // LIBOPENIMSDK_H

#line 1 "cgo-generated-wrapper"


/* End of preamble from import "C" comments.  */


/* Start of boilerplate cgo prologue.  */
#line 1 "cgo-gcc-export-header-prolog"

#ifndef GO_CGO_PROLOGUE_H
#define GO_CGO_PROLOGUE_H

typedef signed char GoInt8;
typedef unsigned char GoUint8;
typedef short GoInt16;
typedef unsigned short GoUint16;
typedef int GoInt32;
typedef unsigned int GoUint32;
typedef long long GoInt64;
typedef unsigned long long GoUint64;
typedef GoInt64 GoInt;
typedef GoUint64 GoUint;
typedef size_t GoUintptr;
typedef float GoFloat32;
typedef double GoFloat64;
#ifdef _MSC_VER
#include <complex.h>
typedef _Fcomplex GoComplex64;
typedef _Dcomplex GoComplex128;
#else
typedef float _Complex GoComplex64;
typedef double _Complex GoComplex128;
#endif

/*
  static assertion to make sure the file is being used on architecture
  at least with matching size of GoInt.
*/
typedef char _check_for_64_bit_pointer_matching_GoInt[sizeof(void*)==64/8 ? 1:-1];

#ifndef GO_CGO_GOSTRING_TYPEDEF
typedef _GoString_ GoString;
#endif
typedef void *GoMap;
typedef void *GoChan;
typedef struct { void *t; void *v; } GoInterface;
typedef struct { void *data; GoInt len; GoInt cap; } GoSlice;

#endif

/* End of boilerplate cgo prologue.  */

#ifdef __cplusplus
extern "C" {
#endif

extern int InitSDK(char* config, char* operationID);
extern void Login(int baseCallbackID, char* uid, char* token, char* operationID);
extern void Logout(int baseCallbackID, char* operationID);
extern int GetLoginStatus(char* operationID);
extern char* GetLoginUserID();

//export UploadFile
extern void UploadFile(int baseCallbackID, int uploadCallbackID, char* operationID, char* reqData);

// Message creation functions (no callback needed)
//
extern char* CreateTextMessage(char* text, char* operationID);
extern char* CreateImageMessage(char* imagePath, char* operationID);
extern char* CreateAdvancedQuoteMessage(char* operationID, char* text, char* message, char* messageEntityList);
extern char* CreateAdvancedTextMessage(char* operationID, char* text, char* messageEntityList);
extern char* CreateSoundMessage(char* soundPath, long long duration, char* operationID);
extern char* CreateFileMessage(char* filePath, char* fileName, char* operationID);
extern char* CreateVideoMessage(char* videoPath, char* videoType, long long duration, char* snapshotPath, char* operationID);
extern char* CreateLocationMessage(char* operationID, char* description, double longitude, double latitude);
extern char* CreateCustomMessage(char* data, char* extension, char* description, char* operationID);
extern char* CreateQuoteMessage(char* text, char* message, char* operationID);
extern char* CreateFaceMessage(char* operationID, int index, char* data);
extern char* CreateMergerMessage(char* messageList, char* title, char* summaryList, char* operationID);
extern char* CreateForwardMessage(char* message, char* operationID);
extern char* CreateCardMessage(char* operationID, char* params);
extern char* CreateTextAtMessage(char* operationID, char* text, char* atUserIDList, char* atUsersInfo, char* quoteMessage);
extern char* CreateImageMessageByURL(char* operationID, char* sourcePath, char* sourcePicture, char* bigPicture, char* snapshotPicture);
extern char* CreateSoundMessageByURL(char* operationID, char* params);
extern char* CreateVideoMessageByURL(char* operationID, char* params);
extern char* CreateFileMessageByURL(char* operationID, char* params);
extern void SendMessage(int baseCallbackID, int sendReceiptCallbackID, char* message, char* recvID, char* groupID, char* offlinePushInfo, char* operationID, int isOnlineOnly);
extern void SendMessageNotOss(int baseCallbackID, int sendReceiptCallbackID, char* message, char* recvID, char* groupID, char* offlinePushInfo, char* operationID, int isOnlineOnly);

// Message retrieval functions
//
extern void GetAllConversationList(int baseCallbackID, char* operationID);
extern void GetConversationListSplit(int baseCallbackID, char* operationID, int offset, int count);
extern void GetOneConversation(int baseCallbackID, char* operationID, int sessionType, char* isSession);
extern void GetMultipleConversation(int baseCallbackID, char* operationID, char* conversationIDList);
extern void SetConversation(int baseCallbackID, char* operationID, char* conversationID, char* params);
extern char* GetConversationIDBySessionType(char* operationID, char* sourceID, int sessionType);
extern void HideAllConversations(int baseCallbackID, char* operationID);
extern void ClearConversationAndDeleteAllMsg(int baseCallbackID, char* operationID, char* conversationID);
extern void DeleteConversationAndDeleteAllMsg(int baseCallbackID, char* operationID, char* conversationID);
extern void SetConversationDraft(int baseCallbackID, char* operationID, char* conversationID, char* draftText);
extern void SetPinnedConversation(int baseCallbackID, char* operationID, char* conversationID, int isPinned);
extern void GetTotalUnreadMsgCount(int baseCallbackID, char* operationID);
extern void GetConversationRecvMessageOpt(char* operationID, char* conversationIDList);
extern void SearchConversation(int baseCallbackID, char* operationID, char* searchParam);
extern void SearchLocalMessages(int baseCallbackID, char* operationID, char* searchParam);

// Message history functions
//
extern void GetAdvancedHistoryMessageList(int baseCallbackID, char* operationID, char* getMessageOptions);
extern void GetHistoryMessageList(char* operationID, char* conversationID, int count, int startSeq);
extern void FindMessageList(int baseCallbackID, char* operationID, char* findOptions);
extern void MarkConversationMessageAsRead(int baseCallbackID, char* operationID, char* conversationID);
extern void MarkMessagesAsReadByMsgID(int baseCallbackID, char* operationID, char* conversationID, char* clientMsgIDs);
extern void MarkAllConversationMessageAsRead(int baseCallbackID, char* operationID);
extern void DeleteMessageFromLocalStorage(int baseCallbackID, char* operationID, char* conversationID, char* seqList);
extern void DeleteMessage(int baseCallbackID, char* operationID, char* conversationID, char* seqList);
extern void DeleteAllMsgFromLocalAndSvr(int baseCallbackID, char* operationID);
extern void InsertSingleMessageToLocal(int baseCallbackID, char* operationID, char* message, char* recvID, char* sendID);
extern void TypingStatusUpdate(int baseCallbackID, char* operationID, char* conversationID, char* msgTip);
extern void ChangeInputStates(int baseCallbackID, char* operationID, char* conversationID, int focus);
extern void GetInputStates(int baseCallbackID, char* operationID, char* conversationID, char* userID);
extern void RevokeMessage(int baseCallbackID, char* operationID, char* conversationID, char* clientMsgID);
extern void DeleteMessageFromLocal(int baseCallbackID, char* operationID, char* conversationID, char* clientMsgID);
extern void DeleteAllMsgFromLocal(int baseCallbackID, char* operationID);
extern void InsertGroupMessageToLocalStorage(int baseCallbackID, char* operationID, char* message, char* groupID, char* sendID);
extern void SetMessageLocalEx(int baseCallbackID, char* operationID, char* conversationID, char* clientMsgID, char* localEx);
extern void SetAppBadge(int baseCallbackID, char* operationID, int appUnreadCount);

// User functions
//
extern void GetUsersInfo(int baseCallbackID, char* operationID, char* userIDList);
extern void GetSelfUserInfo(int baseCallbackID, char* operationID);
extern void SetSelfInfo(int baseCallbackID, char* operationID, char* userInfo);
extern void SetSelfInfoEx(char* operationID, char* userInfo);
extern void GetUserStatus(int baseCallbackID, char* operationID, char* userIDList);
extern void SubscribeUsersStatus(int baseCallbackID, char* operationID, char* userIDList);
extern void UnsubscribeUsersStatus(int baseCallbackID, char* operationID, char* userIDList);
extern void GetSubscribeUsersStatus(int baseCallbackID, char* operationID);
extern void SetAppBackgroundStatus(int baseCallbackID, char* operationID, int isBackground);
extern void NetworkStatusChanged(int baseCallbackID, char* operationID);
extern void CreateGroup(int baseCallbackID, char* operationID, char* groupInfo);
extern void GetJoinedGroupList(int baseCallbackID, char* operationID);
extern void GetGroupsInfo(int baseCallbackID, char* operationID, char* groupIDList);
extern void SetGroupInfo(int baseCallbackID, char* operationID, char* groupInfo);
extern void SetGroupInfoEx(char* operationID, char* groupInfo);
extern void GetJoinedGroupListPage(int baseCallbackID, char* operationID, int offset, int count);
extern void ChangeGroupMute(int baseCallbackID, char* operationID, char* groupID, int isMute);
extern void ChangeGroupMemberMute(int baseCallbackID, char* operationID, char* groupID, char* userID, long long mutedSeconds);
extern void GetGroupMemberList(int baseCallbackID, char* operationID, char* groupID, int filter, int offset, int count);
extern void GetGroupMemberOwnerAndAdmin(int baseCallbackID, char* operationID, char* groupID);
extern void GetUsersInGroup(int baseCallbackID, char* operationID, char* groupID, char* userIDList);
extern void SearchGroupMembers(int baseCallbackID, char* operationID, char* searchParam);
extern void SetGroupMemberInfo(int baseCallbackID, char* operationID, char* groupMemberInfo);
extern void InviteUserToGroup(int baseCallbackID, char* operationID, char* groupID, char* userIDList, char* reason);
extern void KickGroupMember(int baseCallbackID, char* operationID, char* groupID, char* userIDList, char* reason);
extern void GetGroupApplicationUnhandledCount(int baseCallbackID, char* operationID, char* req);
extern void AcceptGroupApplication(int baseCallbackID, char* operationID, char* groupID, char* userID, char* handleMsg);
extern void RefuseGroupApplication(int baseCallbackID, char* operationID, char* groupID, char* userID, char* handleMsg);
extern void TransferGroupOwner(int baseCallbackID, char* operationID, char* groupID, char* newOwnerUserID);
extern void QuitGroup(int baseCallbackID, char* operationID, char* groupID);
extern void DismissGroup(int baseCallbackID, char* operationID, char* groupID);
extern void GetSendMessageOpt(char* operationID, char* groupID);
extern void GetGroupApplicationListAsRecipient(int baseCallbackID, char* operationID, char* req);
extern void GetGroupApplicationListAsApplicant(int baseCallbackID, char* operationID, char* req);
extern void JoinGroup(int baseCallbackID, char* operationID, char* groupID, char* reqMsg, int joinSource, char* ex);
extern void SearchGroups(int baseCallbackID, char* operationID, char* searchParam);
extern void IsJoinGroup(int baseCallbackID, char* operationID, char* groupID);
extern void GetSpecifyFriendsInfo(int baseCallbackID, char* operationID, char* userIDList, int filterBlack);
extern void GetFriendList(int baseCallbackID, char* operationID, int filterBlack);
extern void GetFriendListPage(int baseCallbackID, char* operationID, int offset, int count, int filterBlack);
extern void SearchFriends(int baseCallbackID, char* operationID, char* searchParam);
extern void CheckFriend(int baseCallbackID, char* operationID, char* userIDList);
extern void AddFriend(int baseCallbackID, char* operationID, char* userIDReqMsg);
extern void UpdateFriends(int baseCallbackID, char* operationID, char* req);
extern void DeleteFriend(int baseCallbackID, char* operationID, char* friendUserID);
extern void GetFriendApplicationListAsRecipient(int baseCallbackID, char* operationID, char* req);
extern void GetFriendApplicationListAsApplicant(int baseCallbackID, char* operationID, char* req);
extern void AcceptFriendApplication(int baseCallbackID, char* operationID, char* userIDHandleMsg);
extern void RefuseFriendApplication(int baseCallbackID, char* operationID, char* userIDHandleMsg);
extern void AddBlack(int baseCallbackID, char* operationID, char* blackUserID, char* ex);
extern void GetBlackList(int baseCallbackID, char* operationID);
extern void RemoveBlack(int baseCallbackID, char* operationID, char* removeUserID);
extern void GetFriendApplicationUnhandledCount(int baseCallbackID, char* operationID, char* req);
extern void SetFriendRemark(int baseCallbackID, char* operationID, char* friendUserID, char* remark);
extern void UpdateFcmToken(int baseCallbackID, char* operationID, char* fcmToken, long long expireTime);
extern void Logs(int baseCallbackID, char* operationID, int logLevel, char* file, long long line, char* msgs, char* err, char* keyAndValue);
extern char* GetSdkVersion();
extern void UnInitSDK(char* operationID);
extern void FreeString(char* str);
extern char* GetAtAllTag(char* operationID);
extern char* CreateFileMessageFromFullPath(char* operationID, char* fileFullPath, char* fileName);
extern char* CreateSoundMessageFromFullPath(char* operationID, char* soundPath, long long duration);
extern char* CreateVideoMessageFromFullPath(char* operationID, char* videoFullPath, char* videoType, long long duration, char* snapshotFullPath);
extern void GetAdvancedHistoryMessageListReverse(int baseCallbackID, char* operationID, char* getMessageOptions);
extern void GetSpecifiedGroupMembersInfo(int baseCallbackID, char* operationID, char* groupID, char* userIDList);
extern void UploadLogs(int baseCallbackID, int uploadLogsCallbackID, char* operationID, int line, char* ex);
extern void GetGroupMemberListByJoinTimeFilter(int baseCallbackID, char* operationID, char* groupID, long long offset, long long count, long long joinTimeBegin, long long joinTimeEnd, char* filterUserIDList);

#ifdef __cplusplus
}
#endif
