/* Code generated by cmd/cgo; DO NOT EDIT. */

/* package github.com/openimsdk/openim-sdk-core/v3/native */


#line 1 "cgo-builtin-export-prolog"

#include <stddef.h>

#ifndef GO_CGO_EXPORT_PROLOGUE_H
#define GO_CGO_EXPORT_PROLOGUE_H

#ifndef GO_CGO_GOSTRING_TYPEDEF
typedef struct { const char *p; ptrdiff_t n; } _GoString_;
extern size_t _GoStringLen(_GoString_ s);
extern const char *_GoStringPtr(_GoString_ s);
#endif

#endif

/* Start of preamble from import "C" comments.  */


#line 17 "harmony_bridge.go"

#ifndef LIBOPENIMSDK_H
#define LIBOPENIMSDK_H

#include <stdlib.h>

// Callback types
typedef void (*ConnNoMsgCb)(int);
typedef void (*ConnWithMsgCb)(int, char*);
typedef void (*InfoCb)(char*);
typedef void (*ReceiptCb)(char*);
typedef void (*DeletedCb)(char*);
typedef void (*SyncBoolCb)(int);
typedef void (*SyncProgressCb)(int);
typedef void (*UnreadCb)(int);

// Storage for callbacks (index 0 is used)
#define CB_MAX 64
static ConnNoMsgCb gConnConnecting[CB_MAX];
static ConnNoMsgCb gConnSuccess[CB_MAX];
static ConnWithMsgCb gConnFailed[CB_MAX];
static ConnNoMsgCb gConnKicked[CB_MAX];
static ConnNoMsgCb gConnTokenExpired[CB_MAX];
static ConnWithMsgCb gConnTokenInvalid[CB_MAX];

static InfoCb gRecvNewMsg[CB_MAX];
static ReceiptCb gRecvReceipt[CB_MAX];
static InfoCb gMsgRevoked[CB_MAX];
static InfoCb gRecvOffline[CB_MAX];
static DeletedCb gMsgDeleted[CB_MAX];
static InfoCb gRecvOnline[CB_MAX];

static SyncBoolCb gSyncStart[CB_MAX];
static SyncBoolCb gSyncFinish[CB_MAX];
static SyncProgressCb gSyncProgress[CB_MAX];
static SyncBoolCb gSyncFailed[CB_MAX];
static InfoCb gConvChanged[CB_MAX];
static InfoCb gNewConv[CB_MAX];
static UnreadCb gUnreadChanged[CB_MAX];
static InfoCb gInputStatus[CB_MAX];

static InfoCb gGroupJoinedAdd[CB_MAX];
static InfoCb gGroupJoinedDel[CB_MAX];
static InfoCb gGroupMemberAdd[CB_MAX];
static InfoCb gGroupMemberDel[CB_MAX];
static InfoCb gGroupAppAdd[CB_MAX];
static InfoCb gGroupAppDel[CB_MAX];
static InfoCb gGroupInfoChanged[CB_MAX];
static InfoCb gGroupDismissed[CB_MAX];
static InfoCb gGroupMemberInfo[CB_MAX];
static InfoCb gGroupAppAccept[CB_MAX];
static InfoCb gGroupAppReject[CB_MAX];

static InfoCb gFriendAppAdd[CB_MAX];
static InfoCb gFriendAppDel[CB_MAX];
static InfoCb gFriendAppAccept[CB_MAX];
static InfoCb gFriendAppReject[CB_MAX];
static InfoCb gFriendAdd[CB_MAX];
static InfoCb gFriendDel[CB_MAX];
static InfoCb gFriendInfo[CB_MAX];
static InfoCb gBlackAdd[CB_MAX];
static InfoCb gBlackDel[CB_MAX];

static InfoCb gSelfInfo[CB_MAX];
static InfoCb gUserStatus[CB_MAX];

// Signaling callback type
typedef void (*SignalingCb)(char*);
static SignalingCb gSignalingReceiveNewInvitation[CB_MAX];
static SignalingCb gSignalingInviteeAccepted[CB_MAX];
static SignalingCb gSignalingInviteeAcceptedByOtherDevice[CB_MAX];
static SignalingCb gSignalingInviteeRejected[CB_MAX];
static SignalingCb gSignalingInviteeRejectedByOtherDevice[CB_MAX];
static SignalingCb gSignalingInvitationCancelled[CB_MAX];
static SignalingCb gSignalingInvitationTimeout[CB_MAX];
static SignalingCb gSignalingHangUp[CB_MAX];
static SignalingCb gSignalingRoomParticipantConnected[CB_MAX];
static SignalingCb gSignalingRoomParticipantDisconnected[CB_MAX];

// Custom business callback
typedef void (*CustomBusinessCb)(char*);
static CustomBusinessCb gCustomBusiness[CB_MAX];

// Message kv info callback
typedef void (*MsgKvInfoCb)(char*);
static MsgKvInfoCb gMsgKvInfoChanged[CB_MAX];

// Upload callbacks
typedef void (*UploadOpenCb)(int, long long);
typedef void (*UploadPartSizeCb)(int, long long, int);
typedef void (*UploadHashProgressCb)(int, int, long long, char*);
typedef void (*UploadHashCompleteCb)(int, char*, char*);
typedef void (*UploadIDCb)(int, char*);
typedef void (*UploadPartCompleteCb)(int, int, long long, char*);
typedef void (*UploadCompleteCb)(int, long long, long long, long long);
typedef void (*UploadFinishCb)(int, long long, char*, int);

static UploadOpenCb gUploadOpen[CB_MAX];
static UploadPartSizeCb gUploadPartSize[CB_MAX];
static UploadHashProgressCb gUploadHashProgress[CB_MAX];
static UploadHashCompleteCb gUploadHashComplete[CB_MAX];
static UploadIDCb gUploadID[CB_MAX];
static UploadPartCompleteCb gUploadPartComplete[CB_MAX];
static UploadCompleteCb gUploadComplete[CB_MAX];
static UploadFinishCb gUploadFinish[CB_MAX];

// Upload log progress callback
typedef void (*UploadLogProgressCb)(int, long long, long long);
static UploadLogProgressCb gUploadLogProgress[CB_MAX];

// Send message callback
typedef void (*SendMsgCb)(int, int);
static SendMsgCb gSendMsg[CB_MAX];

// Base callback type - for OnSuccess/OnError
typedef void (*BaseSuccessCb)(int, char*);
typedef void (*BaseErrorCb)(int, int, char*);
static BaseSuccessCb gBaseSuccess[CB_MAX];
static BaseErrorCb gBaseError[CB_MAX];

// Callbacks - invoked by Go
static void callConnConnecting(int v) { if(gConnConnecting[0]) gConnConnecting[0](v); }
static void callConnSuccess(int v) { if(gConnSuccess[0]) gConnSuccess[0](v); }
static void callConnFailed(int v, char* m) { if(gConnFailed[0]) gConnFailed[0](v, m); }
static void callConnKicked(int v) { if(gConnKicked[0]) gConnKicked[0](v); }
static void callConnTokenExpired(int v) { if(gConnTokenExpired[0]) gConnTokenExpired[0](v); }
static void callConnTokenInvalid(int v, char* m) { if(gConnTokenInvalid[0]) gConnTokenInvalid[0](v, m); }

static void callRecvNewMsg(char* m) { if(gRecvNewMsg[0]) gRecvNewMsg[0](m); }
static void callRecvReceipt(char* m) { if(gRecvReceipt[0]) gRecvReceipt[0](m); }
static void callMsgRevoked(char* m) { if(gMsgRevoked[0]) gMsgRevoked[0](m); }
static void callRecvOffline(char* m) { if(gRecvOffline[0]) gRecvOffline[0](m); }
static void callMsgDeleted(char* m) { if(gMsgDeleted[0]) gMsgDeleted[0](m); }
static void callRecvOnline(char* m) { if(gRecvOnline[0]) gRecvOnline[0](m); }

static void callSyncStart(int v) { if(gSyncStart[0]) gSyncStart[0](v); }
static void callSyncFinish(int v) { if(gSyncFinish[0]) gSyncFinish[0](v); }
static void callSyncProgress(int v) { if(gSyncProgress[0]) gSyncProgress[0](v); }
static void callSyncFailed(int v) { if(gSyncFailed[0]) gSyncFailed[0](v); }
static void callConvChanged(char* m) { if(gConvChanged[0]) gConvChanged[0](m); }
static void callNewConv(char* m) { if(gNewConv[0]) gNewConv[0](m); }
static void callUnreadChanged(int v) { if(gUnreadChanged[0]) gUnreadChanged[0](v); }
static void callInputStatus(char* m) { if(gInputStatus[0]) gInputStatus[0](m); }

static void callGroupJoinedAdd(char* m) { if(gGroupJoinedAdd[0]) gGroupJoinedAdd[0](m); }
static void callGroupJoinedDel(char* m) { if(gGroupJoinedDel[0]) gGroupJoinedDel[0](m); }
static void callGroupMemberAdd(char* m) { if(gGroupMemberAdd[0]) gGroupMemberAdd[0](m); }
static void callGroupMemberDel(char* m) { if(gGroupMemberDel[0]) gGroupMemberDel[0](m); }
static void callGroupAppAdd(char* m) { if(gGroupAppAdd[0]) gGroupAppAdd[0](m); }
static void callGroupAppDel(char* m) { if(gGroupAppDel[0]) gGroupAppDel[0](m); }
static void callGroupInfoChanged(char* m) { if(gGroupInfoChanged[0]) gGroupInfoChanged[0](m); }
static void callGroupDismissed(char* m) { if(gGroupDismissed[0]) gGroupDismissed[0](m); }
static void callGroupMemberInfo(char* m) { if(gGroupMemberInfo[0]) gGroupMemberInfo[0](m); }
static void callGroupAppAccept(char* m) { if(gGroupAppAccept[0]) gGroupAppAccept[0](m); }
static void callGroupAppReject(char* m) { if(gGroupAppReject[0]) gGroupAppReject[0](m); }

static void callFriendAppAdd(char* m) { if(gFriendAppAdd[0]) gFriendAppAdd[0](m); }
static void callFriendAppDel(char* m) { if(gFriendAppDel[0]) gFriendAppDel[0](m); }
static void callFriendAppAccept(char* m) { if(gFriendAppAccept[0]) gFriendAppAccept[0](m); }
static void callFriendAppReject(char* m) { if(gFriendAppReject[0]) gFriendAppReject[0](m); }
static void callFriendAdd(char* m) { if(gFriendAdd[0]) gFriendAdd[0](m); }
static void callFriendDel(char* m) { if(gFriendDel[0]) gFriendDel[0](m); }
static void callFriendInfo(char* m) { if(gFriendInfo[0]) gFriendInfo[0](m); }
static void callBlackAdd(char* m) { if(gBlackAdd[0]) gBlackAdd[0](m); }
static void callBlackDel(char* m) { if(gBlackDel[0]) gBlackDel[0](m); }

static void callSelfInfo(char* m) { if(gSelfInfo[0]) gSelfInfo[0](m); }
static void callUserStatus(char* m) { if(gUserStatus[0]) gUserStatus[0](m); }

// Signaling callbacks
static void callSignalingReceiveNewInvitation(char* m) { if(gSignalingReceiveNewInvitation[0]) gSignalingReceiveNewInvitation[0](m); }
static void callSignalingInviteeAccepted(char* m) { if(gSignalingInviteeAccepted[0]) gSignalingInviteeAccepted[0](m); }
static void callSignalingInviteeAcceptedByOtherDevice(char* m) { if(gSignalingInviteeAcceptedByOtherDevice[0]) gSignalingInviteeAcceptedByOtherDevice[0](m); }
static void callSignalingInviteeRejected(char* m) { if(gSignalingInviteeRejected[0]) gSignalingInviteeRejected[0](m); }
static void callSignalingInviteeRejectedByOtherDevice(char* m) { if(gSignalingInviteeRejectedByOtherDevice[0]) gSignalingInviteeRejectedByOtherDevice[0](m); }
static void callSignalingInvitationCancelled(char* m) { if(gSignalingInvitationCancelled[0]) gSignalingInvitationCancelled[0](m); }
static void callSignalingInvitationTimeout(char* m) { if(gSignalingInvitationTimeout[0]) gSignalingInvitationTimeout[0](m); }
static void callSignalingHangUp(char* m) { if(gSignalingHangUp[0]) gSignalingHangUp[0](m); }
static void callSignalingRoomParticipantConnected(char* m) { if(gSignalingRoomParticipantConnected[0]) gSignalingRoomParticipantConnected[0](m); }
static void callSignalingRoomParticipantDisconnected(char* m) { if(gSignalingRoomParticipantDisconnected[0]) gSignalingRoomParticipantDisconnected[0](m); }

// Custom business callback
static void callCustomBusiness(char* m) { if(gCustomBusiness[0]) gCustomBusiness[0](m); }

// Message kv info callback
static void callMsgKvInfoChanged(char* m) { if(gMsgKvInfoChanged[0]) gMsgKvInfoChanged[0](m); }

// Upload callbacks
static void callUploadOpen(int cb, long long s) { if(gUploadOpen[cb]) gUploadOpen[cb](cb, s); }
static void callUploadPartSize(int cb, long long s, int n) { if(gUploadPartSize[cb]) gUploadPartSize[cb](cb, s, n); }
static void callUploadHashProgress(int cb, int i, long long s, char* h) { if(gUploadHashProgress[cb]) gUploadHashProgress[cb](cb, i, s, h); }
static void callUploadHashComplete(int cb, char* p, char* f) { if(gUploadHashComplete[cb]) gUploadHashComplete[cb](cb, p, f); }
static void callUploadID(int cb, char* u) { if(gUploadID[cb]) gUploadID[cb](cb, u); }
static void callUploadPartComplete(int cb, int i, long long s, char* h) { if(gUploadPartComplete[cb]) gUploadPartComplete[cb](cb, i, s, h); }
static void callUploadComplete(int cb, long long f, long long s, long long st) { if(gUploadComplete[cb]) gUploadComplete[cb](cb, f, s, st); }
static void callUploadFinish(int cb, long long s, char* u, int t) { if(gUploadFinish[cb]) gUploadFinish[cb](cb, s, u, t); }

// Upload log progress callback
static void callUploadLogProgress(int cb, long long c, long long t) { if(gUploadLogProgress[cb]) gUploadLogProgress[cb](cb, c, t); }

static void callSendMsg(int cb, int v) { if(gSendMsg[cb]) gSendMsg[cb](cb, v); }
static void callBaseSuccess(int cb, char* d) { if(gBaseSuccess[cb]) gBaseSuccess[cb](cb, d); }
static void callBaseError(int cb, int code, char* m) { if(gBaseError[cb]) gBaseError[cb](cb, code, m); }

#endif // LIBOPENIMSDK_H

#line 1 "cgo-generated-wrapper"


/* End of preamble from import "C" comments.  */


/* Start of boilerplate cgo prologue.  */
#line 1 "cgo-gcc-export-header-prolog"

#ifndef GO_CGO_PROLOGUE_H
#define GO_CGO_PROLOGUE_H

typedef signed char GoInt8;
typedef unsigned char GoUint8;
typedef short GoInt16;
typedef unsigned short GoUint16;
typedef int GoInt32;
typedef unsigned int GoUint32;
typedef long long GoInt64;
typedef unsigned long long GoUint64;
typedef GoInt64 GoInt;
typedef GoUint64 GoUint;
typedef size_t GoUintptr;
typedef float GoFloat32;
typedef double GoFloat64;
#ifdef _MSC_VER
#if !defined(__cplusplus) || _MSVC_LANG <= 201402L
#include <complex.h>
typedef _Fcomplex GoComplex64;
typedef _Dcomplex GoComplex128;
#else
#include <complex>
typedef std::complex<float> GoComplex64;
typedef std::complex<double> GoComplex128;
#endif
#else
typedef float _Complex GoComplex64;
typedef double _Complex GoComplex128;
#endif

/*
  static assertion to make sure the file is being used on architecture
  at least with matching size of GoInt.
*/
typedef char _check_for_64_bit_pointer_matching_GoInt[sizeof(void*)==64/8 ? 1:-1];

#ifndef GO_CGO_GOSTRING_TYPEDEF
typedef _GoString_ GoString;
#endif
typedef void *GoMap;
typedef void *GoChan;
typedef struct { void *t; void *v; } GoInterface;
typedef struct { void *data; GoInt len; GoInt cap; } GoSlice;

#endif

/* End of boilerplate cgo prologue.  */

#ifdef __cplusplus
extern "C" {
#endif

extern int InitSDK(char* config, char* operationID);
extern void Login(int baseCallbackID, char* uid, char* token, char* operationID);
extern void Logout(int baseCallbackID, char* operationID);
extern int GetLoginStatus(char* operationID);
extern char* GetLoginUserID(void);
extern void UploadFile(int baseCallbackID, int uploadCallbackID, char* operationID, char* reqData);
extern char* CreateTextMessage(char* text, char* operationID);
extern char* CreateImageMessage(char* imagePath, char* operationID);
extern char* CreateAdvancedQuoteMessage(char* operationID, char* text, char* message, char* messageEntityList);
extern char* CreateAdvancedTextMessage(char* operationID, char* text, char* messageEntityList);
extern char* CreateSoundMessage(char* soundPath, long long duration, char* operationID);
extern char* CreateFileMessage(char* filePath, char* fileName, char* operationID);
extern char* CreateVideoMessage(char* videoPath, char* videoType, long long duration, char* snapshotPath, char* operationID);
extern char* CreateLocationMessage(char* operationID, char* description, double longitude, double latitude);
extern char* CreateCustomMessage(char* data, char* extension, char* description, char* operationID);
extern char* CreateQuoteMessage(char* text, char* message, char* operationID);
extern char* CreateFaceMessage(char* operationID, int index, char* data);
extern char* CreateMergerMessage(char* messageList, char* title, char* summaryList, char* operationID);
extern char* CreateForwardMessage(char* message, char* operationID);
extern char* CreateCardMessage(char* operationID, char* params);
extern char* CreateTextAtMessage(char* operationID, char* text, char* atUserIDList, char* atUsersInfo, char* quoteMessage);
extern char* CreateImageMessageByURL(char* operationID, char* sourcePath, char* sourcePicture, char* bigPicture, char* snapshotPicture);
extern char* CreateSoundMessageByURL(char* operationID, char* params);
extern char* CreateVideoMessageByURL(char* operationID, char* params);
extern char* CreateFileMessageByURL(char* operationID, char* params);
extern void SendMessage(int baseCallbackID, int sendReceiptCallbackID, char* message, char* recvID, char* groupID, char* offlinePushInfo, char* operationID, int isOnlineOnly);
extern void SendMessageNotOss(int baseCallbackID, int sendReceiptCallbackID, char* message, char* recvID, char* groupID, char* offlinePushInfo, char* operationID, int isOnlineOnly);
extern void GetAllConversationList(int baseCallbackID, char* operationID);
extern void GetConversationListSplit(int baseCallbackID, char* operationID, int offset, int count);
extern void GetOneConversation(int baseCallbackID, char* operationID, int sessionType, char* isSession);
extern void GetMultipleConversation(int baseCallbackID, char* operationID, char* conversationIDList);
extern void SetConversation(int baseCallbackID, char* operationID, char* conversationID, char* params);
extern char* GetConversationIDBySessionType(char* operationID, char* sourceID, int sessionType);
extern void HideAllConversations(int baseCallbackID, char* operationID);
extern void ClearConversationAndDeleteAllMsg(int baseCallbackID, char* operationID, char* conversationID);
extern void DeleteConversationAndDeleteAllMsg(int baseCallbackID, char* operationID, char* conversationID);
extern void SetConversationDraft(int baseCallbackID, char* operationID, char* conversationID, char* draftText);
extern void SetPinnedConversation(int baseCallbackID, char* operationID, char* conversationID, int isPinned);
extern void GetTotalUnreadMsgCount(int baseCallbackID, char* operationID);
extern void GetConversationRecvMessageOpt(char* operationID, char* conversationIDList);
extern void SearchConversation(int baseCallbackID, char* operationID, char* searchParam);
extern void SearchLocalMessages(int baseCallbackID, char* operationID, char* searchParam);
extern void GetAdvancedHistoryMessageList(int baseCallbackID, char* operationID, char* getMessageOptions);
extern void GetHistoryMessageList(char* operationID, char* conversationID, int count, int startSeq);
extern void FindMessageList(int baseCallbackID, char* operationID, char* findOptions);
extern void MarkConversationMessageAsRead(int baseCallbackID, char* operationID, char* conversationID);
extern void MarkMessagesAsReadByMsgID(int baseCallbackID, char* operationID, char* conversationID, char* clientMsgIDs);
extern void MarkAllConversationMessageAsRead(int baseCallbackID, char* operationID);
extern void DeleteMessageFromLocalStorage(int baseCallbackID, char* operationID, char* conversationID, char* seqList);
extern void DeleteMessage(int baseCallbackID, char* operationID, char* conversationID, char* seqList);
extern void DeleteAllMsgFromLocalAndSvr(int baseCallbackID, char* operationID);
extern void InsertSingleMessageToLocal(int baseCallbackID, char* operationID, char* message, char* recvID, char* sendID);
extern void TypingStatusUpdate(int baseCallbackID, char* operationID, char* conversationID, char* msgTip);
extern void ChangeInputStates(int baseCallbackID, char* operationID, char* conversationID, int focus);
extern void GetInputStates(int baseCallbackID, char* operationID, char* conversationID, char* userID);
extern void RevokeMessage(int baseCallbackID, char* operationID, char* conversationID, char* clientMsgID);
extern void DeleteMessageFromLocal(int baseCallbackID, char* operationID, char* conversationID, char* clientMsgID);
extern void DeleteAllMsgFromLocal(int baseCallbackID, char* operationID);
extern void InsertGroupMessageToLocalStorage(int baseCallbackID, char* operationID, char* message, char* groupID, char* sendID);
extern void SetMessageLocalEx(int baseCallbackID, char* operationID, char* conversationID, char* clientMsgID, char* localEx);
extern void SetAppBadge(int baseCallbackID, char* operationID, int appUnreadCount);
extern void GetUsersInfo(int baseCallbackID, char* operationID, char* userIDList);
extern void GetSelfUserInfo(int baseCallbackID, char* operationID);
extern void SetSelfInfo(int baseCallbackID, char* operationID, char* userInfo);
extern void SetSelfInfoEx(char* operationID, char* userInfo);
extern void GetUserStatus(int baseCallbackID, char* operationID, char* userIDList);
extern void SubscribeUsersStatus(int baseCallbackID, char* operationID, char* userIDList);
extern void UnsubscribeUsersStatus(int baseCallbackID, char* operationID, char* userIDList);
extern void GetSubscribeUsersStatus(int baseCallbackID, char* operationID);
extern void SetAppBackgroundStatus(int baseCallbackID, char* operationID, int isBackground);
extern void NetworkStatusChanged(int baseCallbackID, char* operationID);
extern void SetGlobalRecvMessageOpt(int baseCallbackID, char* operationID, int recvOpt);
extern void CreateGroup(int baseCallbackID, char* operationID, char* groupInfo);
extern void GetJoinedGroupList(int baseCallbackID, char* operationID);
extern void GetGroupsInfo(int baseCallbackID, char* operationID, char* groupIDList);
extern void SetGroupInfo(int baseCallbackID, char* operationID, char* groupInfo);
extern void SetGroupInfoEx(char* operationID, char* groupInfo);
extern void GetJoinedGroupListPage(int baseCallbackID, char* operationID, int offset, int count);
extern void ChangeGroupMute(int baseCallbackID, char* operationID, char* groupID, int isMute);
extern void ChangeGroupMemberMute(int baseCallbackID, char* operationID, char* groupID, char* userID, long long mutedSeconds);
extern void GetGroupMemberList(int baseCallbackID, char* operationID, char* groupID, int filter, int offset, int count);
extern void GetGroupMemberOwnerAndAdmin(int baseCallbackID, char* operationID, char* groupID);
extern void GetUsersInGroup(int baseCallbackID, char* operationID, char* groupID, char* userIDList);
extern void SearchGroupMembers(int baseCallbackID, char* operationID, char* searchParam);
extern void SetGroupMemberInfo(int baseCallbackID, char* operationID, char* groupMemberInfo);
extern void InviteUserToGroup(int baseCallbackID, char* operationID, char* groupID, char* userIDList, char* reason);
extern void KickGroupMember(int baseCallbackID, char* operationID, char* groupID, char* userIDList, char* reason);
extern void GetGroupApplicationUnhandledCount(int baseCallbackID, char* operationID, char* req);
extern void AcceptGroupApplication(int baseCallbackID, char* operationID, char* groupID, char* userID, char* handleMsg);
extern void RefuseGroupApplication(int baseCallbackID, char* operationID, char* groupID, char* userID, char* handleMsg);
extern void TransferGroupOwner(int baseCallbackID, char* operationID, char* groupID, char* newOwnerUserID);
extern void QuitGroup(int baseCallbackID, char* operationID, char* groupID);
extern void DismissGroup(int baseCallbackID, char* operationID, char* groupID);
extern void GetSendMessageOpt(char* operationID, char* groupID);
extern void GetGroupApplicationListAsRecipient(int baseCallbackID, char* operationID, char* req);
extern void GetGroupApplicationListAsApplicant(int baseCallbackID, char* operationID, char* req);
extern void JoinGroup(int baseCallbackID, char* operationID, char* groupID, char* reqMsg, int joinSource, char* ex);
extern void SearchGroups(int baseCallbackID, char* operationID, char* searchParam);
extern void IsJoinGroup(int baseCallbackID, char* operationID, char* groupID);
extern void GetSpecifyFriendsInfo(int baseCallbackID, char* operationID, char* userIDList, int filterBlack);
extern void GetFriendList(int baseCallbackID, char* operationID, int filterBlack);
extern void GetFriendListPage(int baseCallbackID, char* operationID, int offset, int count, int filterBlack);
extern void SearchFriends(int baseCallbackID, char* operationID, char* searchParam);
extern void CheckFriend(int baseCallbackID, char* operationID, char* userIDList);
extern void AddFriend(int baseCallbackID, char* operationID, char* userIDReqMsg);
extern void UpdateFriends(int baseCallbackID, char* operationID, char* req);
extern void DeleteFriend(int baseCallbackID, char* operationID, char* friendUserID);
extern void GetFriendApplicationListAsRecipient(int baseCallbackID, char* operationID, char* req);
extern void GetFriendApplicationListAsApplicant(int baseCallbackID, char* operationID, char* req);
extern void AcceptFriendApplication(int baseCallbackID, char* operationID, char* userIDHandleMsg);
extern void RefuseFriendApplication(int baseCallbackID, char* operationID, char* userIDHandleMsg);
extern void AddBlack(int baseCallbackID, char* operationID, char* blackUserID, char* ex);
extern void GetBlackList(int baseCallbackID, char* operationID);
extern void RemoveBlack(int baseCallbackID, char* operationID, char* removeUserID);
extern void GetFriendApplicationUnhandledCount(int baseCallbackID, char* operationID, char* req);
extern void SetFriendRemark(int baseCallbackID, char* operationID, char* friendUserID, char* remark);
extern void UpdateFcmToken(int baseCallbackID, char* operationID, char* fcmToken, long long expireTime);
extern void Logs(int baseCallbackID, char* operationID, int logLevel, char* file, long long line, char* msgs, char* err, char* keyAndValue);
extern char* GetSdkVersion(void);
extern void UnInitSDK(char* operationID);
extern void FreeString(char* str);
extern char* GetAtAllTag(char* operationID);
extern char* CreateFileMessageFromFullPath(char* operationID, char* fileFullPath, char* fileName);
extern char* CreateSoundMessageFromFullPath(char* operationID, char* soundPath, long long duration);
extern char* CreateVideoMessageFromFullPath(char* operationID, char* videoFullPath, char* videoType, long long duration, char* snapshotFullPath);
extern void GetAdvancedHistoryMessageListReverse(int baseCallbackID, char* operationID, char* getMessageOptions);
extern void GetSpecifiedGroupMembersInfo(int baseCallbackID, char* operationID, char* groupID, char* userIDList);
extern void UploadLogs(int baseCallbackID, int uploadLogsCallbackID, char* operationID, int line, char* ex);
extern void GetGroupMemberListByJoinTimeFilter(int baseCallbackID, char* operationID, char* groupID, long long offset, long long count, long long joinTimeBegin, long long joinTimeEnd, char* filterUserIDList);
extern void RegisterConnListener(int onConnecting, int onConnectSuccess, int onConnectFailed, int onKickedOffline, int onUserTokenExpired, int onUserTokenInvalid);
extern void RegisterMsgListener(int onRecvNewMsg, int onRecvReceipt, int onMsgRevoked, int onRecvOffline, int onMsgDeleted, int onRecvOnline);
extern void RegisterConvListener(int onSyncStart, int onSyncFinish, int onSyncProgress, int onSyncFailed, int onConvChanged, int onNewConv, int onUnreadChanged, int onInputStatus);
extern void RegisterGroupListener(int onJoinedAdd, int onJoinedDel, int onMemberAdd, int onMemberDel, int onAppAdd, int onAppDel, int onInfoChanged, int onDismissed, int onMemberInfo, int onAppAccept, int onAppReject);
extern void RegisterFriendListener(int onAppAdd, int onAppDel, int onAppAccept, int onAppReject, int onFriendAdd, int onFriendDel, int onFriendInfo, int onBlackAdd, int onBlackDel);
extern void RegisterUserListener(int onSelfInfo, int onUserStatus);
extern void RegisterSignalingListener(int onReceiveNewInvitation, int onInviteeAccepted, int onInviteeAcceptedByOtherDevice, int onInviteeRejected, int onInviteeRejectedByOtherDevice, int onInvitationCancelled, int onInvitationTimeout, int onHangUp, int onRoomParticipantConnected, int onRoomParticipantDisconnected);
extern void RegisterCustomBusinessListener(int onRecvCustomBusinessMessage);
extern void RegisterMsgKvInfoListener(int onMessageKvInfoChanged);
extern void RegisterUploadFileCallback(int uploadCallbackID, int onOpen, int onPartSize, int onHashPartProgress, int onHashPartComplete, int onUploadID, int onUploadPartComplete, int onUploadComplete, int onComplete);
extern void RegisterUploadLogProgress(int uploadLogsCallbackID, int onProgress);
extern void RegisterBaseCallback(int baseCallbackID, int onSuccess, int onError);
extern void RegisterSendMsgCallback(int sendReceiptCallbackID, int onProgress);
extern void UnregisterUploadFileCallback(int uploadCallbackID);
extern void UnregisterUploadLogProgress(int uploadLogsCallbackID);
extern void UnregisterSendMsgCallback(int sendReceiptCallbackID);
extern void UnregisterBaseCallback(int baseCallbackID);
extern void UnregisterAllUploadCallbacks(void);
extern void UnregisterAllListeners(void);
extern void UnregisterConnListener(void);
extern void UnregisterMsgListener(void);
extern void UnregisterConvListener(void);
extern void UnregisterGroupListener(void);
extern void UnregisterFriendListener(void);
extern void UnregisterUserListener(void);
extern void UnregisterSignalingListener(void);
extern void UnregisterCustomBusinessListener(void);
extern void UnregisterMsgKvInfoListener(void);

#ifdef __cplusplus
}
#endif
